-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 08, 2019 at 12:45 AM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.3.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `startups`
--

-- --------------------------------------------------------

--
-- Table structure for table `listestartups`
--

CREATE TABLE `listestartups` (
  `id` int(8) NOT NULL,
  `ownerID` int(8) NOT NULL DEFAULT 1,
  `type` varchar(255) NOT NULL,
  `statut_juridique` varchar(255) NOT NULL,
  `denomination` varchar(255) NOT NULL,
  `date_creation` date NOT NULL,
  `adresse` varchar(255) NOT NULL,
  `effectif` int(8) NOT NULL,
  `telephone_un` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `site_web` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `prenom` varchar(255) NOT NULL,
  `nom` varchar(255) NOT NULL,
  `telephone_deux` varchar(255) NOT NULL,
  `software` int(1) NOT NULL,
  `sous_domaine_soft` text NOT NULL,
  `hardware` int(1) NOT NULL,
  `sous_domaine_hard` text NOT NULL,
  `ict_advance` int(1) NOT NULL,
  `sous_domaine_ict_advance` text NOT NULL,
  `ict_service` int(1) NOT NULL,
  `sous_domaine_ict_service` text NOT NULL,
  `ict_network` int(1) NOT NULL,
  `sous_domaine_ict_network` text NOT NULL,
  `secteur` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `listestartups`
--

INSERT INTO `listestartups` (`id`, `ownerID`, `type`, `statut_juridique`, `denomination`, `date_creation`, `adresse`, `effectif`, `telephone_un`, `email`, `site_web`, `description`, `prenom`, `nom`, `telephone_deux`, `software`, `sous_domaine_soft`, `hardware`, `sous_domaine_hard`, `ict_advance`, `sous_domaine_ict_advance`, `ict_service`, `sous_domaine_ict_service`, `ict_network`, `sous_domaine_ict_network`, `secteur`) VALUES
(1, 1, 'STARTUP', 'SARL', 'Keydjune &amp; AssociÃ©s', '2016-06-17', 'Ouest foire lot 8 villa 67', 10, '338202832', 'keydjune@gmail.com', 'www.keydjuneholding.com', 'IT business,montique et finance.', 'Christian', 'Pape samba gueye', '774241502', 1, 'Développement logiciel métier - Applications web - Applications mobile', 1, 'Terminaux mobiles et accessoires  - équipements monétique', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - big data,  - Drone, robotique - AR/VR (réalités augmentées/réalités virtuelles), - Blockchain', 1, 'E-Payement, Fintech - E-commerce - E-tourisme', 1, 'Services réseaux - Hosting, cloud', 'Economie Sociale &amp; Solidaire  - Banque, finance, assurances  - Sport, Jeux vidÃ©o, Loisirs &amp; Tourisme  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Technologies d entreprises -gÃ©nÃ©ralistes  - Transport, Logistique - Digital Culture et agilitÃ©'),
(2, 1, 'STARTUP', 'GIE', 'NIFRITECH', '2017-11-14', 'Dakar Fann Bel Air', 0, '+221 78 420 37 94', 'anicet.kiemde@nifritech.com', 'www.nifritech.com', 'Formation et coaching certification  - IngÃ©nierie fibre optique et rÃ©seaux  - DÃ©veloppement d\'application - SÃ©curitÃ© des SI - IOT', 'Sountongnoma Martial Anicet', 'KIEMDE', '', 1, 'Applications web - Applications mobile', 1, 'Composants électroniques et assemblage ', 1, 'IoT (internet des objets),  - Drone, robotique', 1, 'Sécurité, monitoring', 1, 'Télécoms - Services réseaux', 'Agriculture, Ã©levage ; environnement, pÃ¨che - SÃ©curitÃ© et Cyber sÃ©curitÃ© - Education, Formation, RH, Recherche - TÃ©lÃ©communications '),
(3, 1, 'STARTUP', 'SARL', 'linkmoney &amp; ntic', '2018-01-25', 'mermoz 155 x VDN', 5, '778177919', 'christian.linkmoneyntic@gmail.com', 'www.linkmoneyntic.com', 'reprÃ©sentant exclusif de grandes industries de terminaux MPOS,ATM-Machine, Bornes, Compteuses Trieuses de billets,Agence Digitale, avec les Tellers machines, Gateway et Swift. - Nous offrons Ã  nos partenaires toutes les solutions monÃ©tiques HardWare et SoftWare.', 'christian', 'lengha lengha', '774241502', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Composants électroniques et assemblage  - Ordinateurs et équipements informatiques - Autres équipements', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - big data,  - Drone, robotique - AR/VR (réalités augmentées/réalités virtuelles),', 1, 'Sécurité, monitoring - E-Payement, Fintech - E-commerce - E-éducation', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp; export  - Economie Sociale &amp; Solidaire  - Banque, finance, assurances  - Sport, Jeux vidï¿½o, Loisirs &amp; Tourisme  - Marketing et Communication  - Mï¿½dia sociaux/Rï¿½seaux Sociaux  - Sï¿½curitï¿½ et Cyber sï¿½curitï¿½  - Technologies dï¿½entreprises gï¿½nï¿½ralistes  - Tï¿½lï¿½communications '),
(4, 1, 'STARTUP', 'SARL', 'Startup Xayma Mbay', '2018-05-16', 'Université Gaston Berger Saint-L1s du SENEGAL', 3, '774594319', 'assanemoussa24@gmail.com', '', 'Xayma Mbay est une plateforme collaborative qui interconnecte les acteurs de l\'écosystéme agricole.', 'ASSANE', 'GUEYE', '774594319', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires ', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - big data, ', 1, 'Sécurité, monitoring - E-Payement, Fintech - E-commerce - E-agriculture - E-éducation', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Agriculture, élevage ; environnement, péche - Technologies déentreprises généralistes '),
(5, 1, 'STARTUP', 'SARL', 'SUGU SAS', '2017-03-17', 'sacre coeur 3 villa 10053', 21, '338592581', 'yam@1carry.com', 'WWW.1CARRY.COM', 'entreprise de logistique crossboarder spécialisé sur le e-commerce', 'oumar', 'yam', '771178595', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Commerce, agroalimentaire, distribution, import & export  - Transport, Logistique'),
(6, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'PratiSIG Consulting ', '2017-09-01', '125 B,  Cité Soprim, Dakar', 5, '771270387', 'pratisig.consulting@gmail.com', 'www.pratisig.tk', 'Offre de formations en Géomatique, Prestation de services en SIG,  Développement local et sondage', 'Youssoupha ', 'MBODJI ', '771270387', 1, 'Développement logiciel métier - Base de données - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Education, Formation, RH, Recherche'),
(7, 1, 'STARTUP', 'SARL', 'IPANEL SARL', '2016-01-01', '', 0, '773472497', 'moulaye.aidara@ipanel-education.com', 'www.ipanel-education.com', 'Léobjectif de léInstitut Panafricain déEnseignement en Ligne é IPANEL est déapporter une contribution dans la promotion et le développement de la formation é distance. Il séagit déaider é la définition et é léamélioration des programmes et projets de formation et le renforcement des capacités pour un meilleur développement national de la formation é distance. La démarche consiste é identifier et é prendre en compte tous les aspects humains, matériels, techniques et financiers afin déadopter les meilleures pratiques possibles tout en dégageant des leviers de rentabilité économique.', 'Moulaye', 'AIDARA', '773472497', 0, '', 0, '', 0, '', 1, 'E-éducation', 0, '', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Energie et énergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Marketing et Communication  - Mode, beauté, luxe  - Aménagement déintérieur et déextérieur  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Sécurité et Cyber sécurité  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Industrie, Mines - Technologies déentreprises généralistes  - Télécommunications  - Transport, Logistique'),
(8, 1, 'STARTUP', 'SUARL', 'SYSLAB', '2018-08-17', 'Ngor Virage Lot Né 56', 8, '339593258', 'contact@syslab.sn', 'www.syslab.sn', 'Agence digitale - Stratégies d\'entreprise', 'Ngagne', 'Top', '773541553', 1, 'Applications web - Applications mobile', 1, 'Signalétique digitale', 1, 'Animation 3D,                                 - Intelligence Artificielle (IA),  - Drone, robotique - AR/VR (réalités augmentées/réalités virtuelles),', 1, 'E-Payement, Fintech - E-commerce - E-agriculture - E-éducation', 1, 'Télécoms - Hosting, cloud', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Energie et énergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Marketing et Communication  - Mode, beauté, luxe  - Aménagement déintérieur et déextérieur  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Sécurité et Cyber sécurité  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Technologies déentreprises généralistes  - Télécommunications  - Transport, Logistique'),
(9, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'EXPERT ACTU', '2017-02-07', 'Dakar, Sénégal Sacré coeur 2', 5, '00221 77 342 45 15 / 00 221 77 839 9437', 'expertactu.officiel@gmail.com', 'https://www.facebook.com/expertactu/', 'EXPERT ACTU, plateforme web media, qui traite l\'information internationale, d\'actualité mondiale, dont l\'ambition est de porter la voix de l\'Afrique hors du continent, et témoigner les opportunités que peut peut offrir internet de nos jours.', 'Abd-El Senguel Florey ', 'MAFOULA', '2.21773E+11', 1, 'Applications web - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Administration/services publics  - Culture, Image, Media ; multimédia, audiovisuel - Marketing et Communication  - Média sociaux/Réseaux Sociaux '),
(10, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'actuvision.com', '2018-01-01', 'RUE 12 X AVENUE BOURGUIBA', 0, '+221773129258', 'actuvisiontv@gmail.com', 'http://actuvision.com/', 'ActuvisionTV  WWW.ACTUVISION.COM - Un Clin d\'oeil Sur l\'Actu  - sit information national international ', 'mohamed lamine ', 'fall', '773129258', 1, 'Base de données', 0, '', 0, '', 0, '', 1, 'Services réseaux', 'Média sociaux/Réseaux Sociaux '),
(11, 1, 'STARTUP', 'SUARL', 'Demarch', '2017-10-20', 'Keur massar sur la route du lac rose', 9, '338970846', 'fbdiop@demarch.sn', 'www.demarch.sn', 'Dématérialisation, archivage numérique, édition numérique, traitement de données', 'Fatou Bintou', 'DIOP', '778639264', 1, 'Production', 1, 'Ordinateurs et équipements informatiques', 0, '', 1, 'Dématérialisation', 0, '', 'Administration/services publics  - Edition'),
(12, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'innov\'digital', '2018-11-13', '3, Rue Béranger Féraud', 10, '+221781735479', 'fayeabdoulaye45@gmail.com', 'www.innovdigital.sn', 'Innov digital est une startup de communication digitale spécialisée dans le développment de logiciels, de l\'infographie, du web-marketing et du développement des solutions monétiques', 'Abdoulaye', 'Faye', '2.21782E+11', 1, 'Développement logiciel métier - Applications web - Applications mobile', 0, '', 1, 'IoT (internet des objets),  - AR/VR (réalités augmentées/réalités virtuelles),', 1, 'E-Payement, Fintech', 1, 'Services réseaux', 'Administration/services publics  - Marketing et Communication  - Média sociaux/Réseaux Sociaux  - Sécurité et Cyber sécurité  - Technologies déentreprises généralistes '),
(13, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'JOBTEL', '2015-06-16', 'point E rue A x 2', 6, '338256110', 'contact@jobtel.sn', 'www.jobtel.sn', 'JOBétel Sénégal un nouveau produit qui consiste é faciliter le quotidien des demandeurs déemploi et aussi les entreprises  - -Une carte déabonnement JOBTEL: MY JOBCARD DEMANDEUR - o	vous permet de recevoir les offres déemploi de maniére automatisé selon votre profil et le domaine de recherche.viasms, email ou messagerie vocal - o	Léaccompagnement sur toute la procédure de recherche du candidat  - Participation déateliers Co-organisés avec nos partenaires - o	Faire votre test de personnalité - o	Bénéficiez de bon de réduction avec la carte - -Une carte déabonnement JOBTEL: MY JOBCARD RECRUTEUR', 'Cheikh Tidiane ', 'Diagne', '774791520', 1, 'Développement logiciel métier - Base de données - Applications web', 1, 'Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires  - intégration de solution', 0, '', 1, 'E-commerce - E-éducation', 1, 'Télécoms - Services réseaux', 'Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Média sociaux/Réseaux Sociaux  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Technologies déentreprises généralistes  - Télécommunications '),
(14, 1, 'STARTUP', 'SARL', 'DG GLOBAL BUSINESS', '2016-05-09', '550 HLM GRAND MEDINE DAKAR', 3, '784576595', 'dgglobus@sen-pass.com', 'www.sen-pass.com', 'DG GLOBUS SARL est une startup é vocation numérique qui travaille dans la conception et la réalisation de plateforme digitale en marque grise, la dématérialisation des procédures, le paiement mobile et léentretien du tourbillon numérique. ', 'Cheikh', 'DIOUF', '784576595', 1, 'Développement logiciel métier', 0, '', 0, '', 1, 'E-Payement, Fintech - E-commerce - E-santé', 0, '', 'Administration/services publics  - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Banque, finance, assurances '),
(15, 1, 'PME/PMI  ', 'SARL', 'ANDANDO SN', '2018-07-24', '37 Cité CPI VDN, Dakar - Sénégal', 6, '2.21338E+11', 'contact@andando.sn', 'https://www.andando.sn', 'ANDANDO est une équipe forte de plusieurs ingénieurs informatiques avec diverses compétences et expériences. Nous sommes une entreprise spécialisée dans les technologies de léinformation et de la communication. Notre expertise concerne principalement deux volets qui sont léIngénierie logicielle et la Sécurité informatique. En plus de ces deux domaines de prédilections, nous sommes réellement engagés dans le tissu social en développement des applications come Andando (covoiturage), Dakar By Bus et Andando Académie (e-learning).', 'Moussa', 'DIALLO', '2.21773E+11', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 1, 'IoT (internet des objets), ', 1, 'Sécurité, monitoring - E-Payement, Fintech - E-éducation', 1, 'Télécoms - Hosting, cloud', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances  - Sécurité et Cyber sécurité  - Education, Formation, RH, Recherche - Télécommunications  - Transport, Logistique'),
(16, 1, 'STARTUP', 'SARL', 'ADNTECH', '2016-01-01', 'Sacre coeur 3', 5, '', 'management@adncorp.com', 'www.adncorp.com', 'Applications de reporting et suivi comptable pour les PME - Applications de reporting réglementaire pour les microfinances - Vente de Licences et Developpement informatique - Expertise : Big Data, Chatbot, Open Innovation', 'ADNCORP', 'DIOP', '776343174', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile - Autres sous domaines', 0, '', 1, 'Intelligence Artificielle (IA),  - big data, ', 0, '', 0, '', 'Banque, finance, assurances  - Restauration, hétellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Technologies déentreprises généralistes '),
(17, 1, '', 'GIE', 'Fineducation for youth', '2018-03-01', 'Scat Urbam Hann Maristes 1', 4, '+ 221 77 690 96 18', 'foryouthfineducation@gmail.com', '', 'Nous travaillons dans le domaine de l\'éducation financiére des jeunes.', 'Mariama', 'NDIAYE', '774895920', 0, '', 0, '', 0, '', 0, '', 0, '', ''),
(18, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'JobsCom', '2017-05-01', 'Diamniadio', 7, '+221785289105', 'Ouzdiop92@gmail.com', '', 'Impression sur support de communication flocage sérigraphie infographie ', 'Ousmane', 'Diop', '785289105', 0, '', 0, '', 0, '', 0, '', 0, '', 'Marketing et Communication  - Mode, beauté, luxe  - Télécommunications '),
(19, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Monetbil Sénégal, Ets', '2018-10-30', 'CTIC Dakar', 1, '763566489', 'thierry.nguefack@boorgeon.com', 'www.monetbil.com', 'Agrégation des méthodes de paiement pour simplifier les achats en ligne.', 'Yves Thierry', 'NGUEFACK Assong', '763566489', 1, 'Applications web - Applications mobile', 0, '', 0, '', 1, 'E-Payement, Fintech', 0, '', 'Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances  - Sport, Jeux vidéo, Loisirs & Tourisme '),
(20, 1, 'STARTUP', 'SAS', 'ZELCASH SAS', '2018-05-02', 'Diorga Chérif, Rufisque', 1, '338368118', 'contact@zel-cash.com', 'zel-cash.com', 'Opération de transfert d\'argent et service financier digitaux.', 'Elhadji Ousmane', 'NDIAYE', '774310305', 0, '', 0, '', 0, '', 0, '', 0, '', 'Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances '),
(21, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Interface', '2017-04-26', 'Sicap Sacré Coeur III Pyrotechnie Lot 85 B 4éme étage', 8, '338250605', 'support@interface.sn', 'www.interface.sn', 'Le nouveau concept trés innovant BEINDAY vous permet 0 seulement déétre  ONLINE  gratuitement via son réseau avec le canal des réseaux sociaux mais aussi de préserver et de protéger notre environnement qui utilise encore, pour la plupart, les supports de communication classiques é base de papier. Contrairement é BEINDAY qui propose léinjection de contenus via le wifi monétisé déoé le slogan é free is green é.', 'Magatte', 'SYLLA', '775419113', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Terminaux mobiles et accessoires ', 1, 'IoT (internet des objets),  - big data, ', 1, 'free wifi', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Administration/services publics  - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Energie et énergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Marketing et Communication  - Média sociaux/Réseaux Sociaux  - Sécurité et Cyber sécurité  - Télécommunications '),
(22, 1, 'PME/PMI  ', 'SUARL', 'Cosmos Multimedia', '2018-03-07', 'SICAP SACRE COEUR 1', 2, '775088500', 'simel80@hotmail.fr', 'EN COURS DE CONSTRUCTION', 'Créée en 2018, notre objectif est déaccompagner les structures PME, PMI dans le développement de leur visibilité sur les supports numériques, mais aussi améliorer léimage de marque sur les nouvelles technologies avec une communication maitrisée basée sur la vidéo web marketing sensoriel (reportage, documentaires, visio Web, mobile, réseaux sociaux...) Nous proposons également des ITV avec des journalistes reporters issus de grands médias. Choisissez votre package de diffusion ( Télévision /media en ligne etc..) Nous nous occupons de Tout ! -  -  - Développement de site web, application Mobile et séc', 'Massamba', 'THIAM', '33674346585', 1, 'Applications web - Applications mobile', 0, '', 0, '', 1, 'Sécurité, monitoring', 1, 'Services réseaux - Hosting, cloud - Conseil en Sécurité Informatique', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Energie et énergies renouvelables - Banque, finance, assurances  - Sport, Jeux vidéo, Loisirs & Tourisme  - Marketing et Communication  - Mode, beauté, luxe  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Emploi, RH, Services é la personne  - Technologies déentreprises généralistes  - Télécommunications '),
(23, 1, 'STARTUP', 'SARL', 'GIGA DEVELOP', '2016-06-16', '1bis rue masclary x allées Robert Delmas', 6, '77 568 00 00', 'gigadevelopsenegal@gmail.com', '', 'GIGA DEVELOP -  Léinnovation technologique au service de la population  - GIGA est spécialisée dans le domaine des nouvelles Technologies de léInformation et de la Communication (T.I.C.) plus particuliérement dans les domaines suivants : - é	Développement de logiciels et déoutils déanalyse de données - é	Systéme de paiement  - é	Objets connectés - é	Systéme de géolocalisation et de tracking - é	Big-Data -  - il crée un environnement déaffaires optimal avec une qualité de service incomparable, participe é placer le Sénégal sur un sentier de croissance plus élevé par léexploitation des avantages comparatifs ', 'Cherif ', 'DJIBA', '775680000', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Ordinateurs et équipements informatiques', 1, 'IoT (internet des objets),  - big data, ', 1, 'E-Payement, Fintech', 0, '', 'Economie Sociale & Solidaire  - Marketing et Communication  - Média sociaux/Réseaux Sociaux  - Technologies déentreprises généralistes  - Transport, Logistique'),
(24, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'AGRITECH-SOLUTIONS', '2018-01-01', 'Dakar,liberté', 1, '778045034', 'techagrisolutions@gmail.com', 'agritechsolutions.sn', 'TIC,agricole', 'Makhtar', 'DIOP', '778045034', 1, 'Développement logiciel métier - Applications web - Applications mobile - Autres sous domaines', 1, 'Composants électroniques et assemblage  - Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires ', 0, '', 0, '', 0, '', ''),
(25, 1, 'STARTUP', 'SARL', 'NOTERKO ', '2018-01-05', '2987D Sicap Dieuppeul 4 Dakar', 2, '776472396', 'contact@noterko.com', 'www.noterko.com', 'Enquétes de satisfaction clients, collecte des données clients, sondage via plateforme NoterKo, formation accueil clientéle ', 'Nancy', 'Camara', '776472396', 1, 'Applications web', 0, '', 1, 'big data, ', 0, '', 1, 'Hosting, cloud', 'Administration/services publics  - Santé, bien é étre  - Banque, finance, assurances  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie '),
(26, 1, 'STARTUP', 'SUARL', 'Black Star Technologies Sénégal', '2017-06-08', 'Villa 1304, HLM Grand-Yoff, Dakar - Sénégal', 30, '2.21339E+11', 'contact@blackstar-tech.com', 'www.blackstar-tech.com', 'Développement d\'applications (web et mobile) dans les 3 domaines suivants: -  - 1 - Solutions de téléphonie d\'entreprise: centre d\'appels, serveurs vocaux, plateforme SMS -  - 2 - Monétique et solutions de paiement électronique (Mobile Banking, eWallet, transfert...) -  - 3 - Biométrie et cartes d\'identification (cartes é puce, cartes magnétiques, PVC...) -  - Services BPO(Externalisation des processus métiers)', 'Mamadou Lamine ', 'KA', '2.21769E+11', 1, 'Développement logiciel métier - Applications web - Applications mobile - Biométrie, monétique, centres d\'appels, serveurs vocaux', 0, 'Ordinateurs et équipements informatiques', 0, '', 0, '', 0, '', 'Administration/services publics  - Banque, finance, assurances  - Télécommunications '),
(27, 1, 'PME/PMI', 'GIE', 'HOUDA SYSTEME', '2009-09-05', 'ANGLE 28 EN FACE STATION MAACK', 4, '33 978 47 44 - 77 844 79 80', 'cheikhouna.houda@gmail.com', '', 'désenveloppent et distribution des logiciels de gestion commerciale et de la comptabilité generale', 'Cheikhouna', 'LO', '778447980', 1, 'Développement logiciel métier - Base de données', 1, 'Ordinateurs et équipements informatiques', 0, '', 0, '', 0, '', 'Commerce, agroalimentaire, distribution, import & export  - Emploi, RH, Services é la personne  - Technologies déentreprises généralistes '),
(28, 1, 'PME/PMI', 'GIE', 'FREELAB', '2016-05-07', 'mamelles cite elevage', 5, '773842905', 'mohamedfall74@gmail.com', '', 'NOUS CONCEVONS DES DISPOSITIFS ELECTRONIQUES DANS PLUSIEURS DOMAINES: SANTE,ENVIRONNEMENT,AGRICULTURE - EX: ELECTROCARDIOGRAMME CONNECTE,SYSTEME D\'IRRIGATION AUTOMATIQUE...', 'mohamed', 'fall', '773842905', 1, 'Applications web', 1, 'Composants électroniques et assemblage  - Terminaux mobiles et accessoires ', 1, 'Animation 3D,                                 - IoT (internet des objets),  - Intelligence Artificielle (IA),  - big data,  - Drone, robotique - AR/VR (réalités augmentées/réalités virtuelles),', 1, 'Sécurité, monitoring - E-santé - E-agriculture - E-éducation', 0, '', 'Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Sécurité et Cyber sécurité  - Technologies déentreprises généralistes '),
(29, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'ADINKRA CONSULTING ', '2018-02-11', 'Ngor, Almadies ', 4, '+221 766132859', 'akomatsrilola@gmail.com', 'www.adinkra-consulting.com', 'ADINKRA Consulting est une agence de communication en Afrique de léOuest, déterminée é aider les entrepreneurs, les organisations socialement responsables et les individus oeuvrant dans les domaines de léagriculture et du développement é avoir un impact social et durable.', 'AKOMATSRI', 'Lola', '766132859', 1, 'Applications web - Applications mobile', 0, '', 0, '', 1, 'E-agriculture - E-éducation', 0, '', 'Agriculture, élevage ; environnement, péche - Marketing et Communication  - Média sociaux/Réseaux Sociaux  - Technologies déentreprises généralistes '),
(30, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'SALOUM TIC SERVICES', '2016-11-24', 'BONGRE KAOLACK', 2, '772057671', 'ndeyemaremen1@gmail.com', '', 'PRESTATAIRE DE FORMATION EN INFORMATIQUE', 'MARIAMA', 'NDIAYE', '772057671', 0, '', 1, 'Terminaux mobiles et accessoires ', 0, '', 1, 'E-Payement, Fintech - E-éducation', 0, '', 'Administration/services publics  - Média sociaux/Réseaux Sociaux  - Education, Formation, RH, Recherche'),
(31, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Adji Informatique', '2017-06-02', 'Rue 57 x 701 Fann Hock', 5, '784513505', 'ibrahima@sentools.net', '', '', 'Ibrahima', 'Sene', '784513505', 1, 'Base de données - Applications web - Applications mobile', 1, 'Composants électroniques et assemblage  - Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires ', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - AR/VR (réalités augmentées/réalités virtuelles),', 0, '', 0, '', 'Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Média sociaux/Réseaux Sociaux  - Sécurité et Cyber sécurité  - Education, Formation, RH, Recherche - Technologies déentreprises généralistes  - Télécommunications '),
(32, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Pragma-tics', '2017-02-16', '1,Rue du Lieutenant Colonel Pierre Faye, Zone A Dakar-Sénégal', 3, '776500852', 'pragmaticsenegal@gmail.com', 'www.pragma-tics.net', 'Pragma-tics est une entreprise informatique spécialisée dans léingénierie logicielle, la conception de sites internet et d\'applications mobiles natives. - Nous concevons des progiciels de gestion hébergés sur notre cloud SaaS et accessibles via les navigateurs Web ne nécessitant aucune installation sur un poste de travail.', ' Papa Amath ', 'Diouf', '776500852', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances  - Média sociaux/Réseaux Sociaux  - Sécurité et Cyber sécurité  - Technologies déentreprises généralistes '),
(33, 1, 'STARTUP', 'SARL', 'COLISDAYS', '2017-03-01', '155 cité des impéts et domaines Patte d\'oie Nord', 0, '777475765', 'contact@colisdays.com', 'www.colisdays.com', 'Colisdays est une plateforme communautaire qui met en relation des expéditeurs avec des voyageurs profitant déun déplacement déjé prévu pour transporter des colis ou documents. -  - Ce systéme gagnant-gagnant favorise un nouveau mode déenvoi et de suivi de colis : pour léexpéditeur, il séagira déavoir un moyen alternatif déenvoyer des colis é des tarifs compétitifs et pour le voyageur de rentabiliser son déplacement en avion ou en voiture par le biais de ses kilos restants.', 'MACTAR', 'SYLLA', '777475765', 0, '', 0, '', 0, '', 1, 'E-commerce - Autres (é préciser)', 0, '', 'Transport, Logistique'),
(34, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Massala Services', '2013-01-01', '99 Cité Djily Mbaye', 1, '+221776275258', 'mouna.mbacke@gmail.com', 'www.e-diaba.com', 'Vente de produits de beauté fabriques par des entrepreneurs africains', 'Maimouna', 'Mbacke', '776275258', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Santé, bien é étre  - Mode, beauté, luxe '),
(35, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'BUUTIC', '2017-02-02', 'Jokkolabs, Sacré coeur 3 Villa Né 9653 , 4eme phase, 41 Voie de degagement N,', 4, '+221781464694', 'buuticservice@gmail.com', 'buutic.business.site', 'Service aux entreprises', 'L1s Dione', 'BIAGUI', '781464694', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires ', 1, 'IoT (internet des objets),  - big data, ', 1, 'E-Payement, Fintech - E-commerce - E-santé - E-agriculture - E-éducation', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Banque, finance, assurances  - Sport, Jeux vidéo, Loisirs & Tourisme  - Marketing et Communication  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Technologies déentreprises généralistes  - Télécommunications '),
(36, 1, 'STARTUP', 'GIE', 'agroproduct consulting group ', '2016-01-01', 'sam kaolack lot 66 angle sp', 4, '781683014', 'francoismariasene@yahoo.fr', '', 'Entreprise agroalimentaire spécialisée dans la production et la transformation du moringa bio ', 'Franéois maria ', 'séne ', '781683014', 0, 'Autres sous domaines', 0, 'Autres équipements', 0, 'Autres (é préciser)', 1, 'E-commerce - E-agriculture', 0, 'agriculture ', 'Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Restauration, hétellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne '),
(37, 1, 'STARTUP', 'GIE', 'Earth Géomatique', '2018-08-07', 'babacarfall.92@gmail.com', 3, '773080399', 'abadjibadji@gmail.com', 'snsig@gmail.com', 'Entreprises offrant des services informatiques accés dans les technologies géospatiales', 'Amezedine younoussa ', 'Badji', '772238635', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 1, 'Animation 3D,                                 - Drone, robotique', 1, 'E-commerce - E-agriculture - E-éducation', 0, '', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Culture, Image, Media ; multimédia, audiovisuel - Marketing et Communication '),
(38, 1, 'STARTUP', 'GIE', 'e-Geo', '1900-01-01', '', 0, '', '', '', '', 'Amzedine Younoussa Ben Yacoub', 'BADJI', '772238635', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 1, 'Animation 3D,                                 - Intelligence Artificielle (IA),  - big data,  - Drone, robotique', 1, 'E-commerce - E-agriculture - E-éducation', 0, '', 'Agriculture, élevage ; environnement, péche - Technologies déentreprises généralistes '),
(39, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Xilembane TELECTRON Sénégal', '2015-06-29', 'Parcelles Assainies U 15', 1, '772319736', 'telectronsenegal@gmail.com', '', 'L\'entreprise devrait fournir des services en sécurité électronique et en infrastructure télécoms et informatique. - Peinant é décoller, je travaille pour une entreprise de la place', 'Papa Birame ', 'BEYE', '772319736', 0, '', 1, 'Composants électroniques et assemblage  - Sécurité électronique et céblage informatique', 0, '', 0, '', 1, 'Télécoms - Services réseaux', 'Administration/services publics  - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Energie et énergies renouvelables - Mode, beauté, luxe  - Sécurité et Cyber sécurité  - Télécommunications '),
(40, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'groupe kawsara', '2011-05-06', 'Rufisque coloban', 102, '774292340', 'cheikhibradieng607@gmail.com', 'wwwgkawsara', 'Envoyé des colis numérique et info', 'cheikh ibra', 'dieng', '774292340', 0, '', 0, '', 0, '', 1, 'E-Payement, Fintech - E-commerce - Transport Logistique', 0, '', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import & export  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Média sociaux/Réseaux Sociaux  - Technologies déentreprises généralistes  - logistiques'),
(41, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'SENDEAL.SN', '2015-06-25', 'Nord foire villa 10,3éme Etage rue prolongée SDE', 5, '770932214', 'sendeal.sn@gmail.com', 'www.sendeal.sn', 'Sendeal.sn  est le pionnier sénégalais de léachat groupé. Nous proposons des bons plans é séoffrir ou é offrir : sport, beauté, bien-étre, restaurants, loisirs, shopping, sorties, voyages... Uniquement des bons plans négociés au meilleur prix chez les commeréants de votre ville. - Sendeal.sn ancre son identité é la frontiére de trois tendances : - -le développement du e-commerce, - -le besoin déacheter moins cher  - -et léaspiration é consommer mieux et proche de chez soi. - Devant un large choix de produits léachat groupé vous permet :De vous offrir des expériences uniques que vous néauriez jamais - ', 'SAIDOU', 'GUISSE', '770932214', 1, 'Développement logiciel métier - Base de données - Applications web - site web et plateforme sms marketing', 0, '', 0, '', 1, 'E-Payement, Fintech - E-commerce - E-agriculture - E-éducation', 0, '', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Marketing et Communication  - Mode, beauté, luxe  - Aménagement déintérieur et déextérieur  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Télécommunications  - Transport, Logistique'),
(42, 1, 'PME/PMI  ', 'SARL', 'DMS Sarl ', '2018-03-01', 'Thies Senegal ', 9, '768502222', 'dmssarlthies@gmail.com', 'www.dmssenegal.com', 'Recyclage et fabrication de tuyaux goute é goute et tube orange ', 'Mamadou ', 'Diaw', '782902071', 0, '', 0, '', 1, 'Animation 3D,                                ', 1, 'E-agriculture - E-éducation', 1, 'Services réseaux', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Energie et énergies renouvelables'),
(43, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'SUPA-DEV', '2018-05-07', '109-B Sicap Mbao', 1, '+221771827530', 'habib92m@gmail.com', 'www.super-dev.com', 'INGéNIERIE LOGICIEL - PRESTATION DE SERVICES - CRéATION ET VENTE DE LOGICIEL -  ', 'Habib Baédy', 'SOW', '2.21772E+11', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Economie Sociale & Solidaire  - Transport, Logistique'),
(44, 1, 'STARTUP', 'SARL', 'Sunubus', '2017-12-20', 'Dakar Sacré coeur Pyrotechnique derriere agence senelec 10600', 5, '+221772704731', 'contact@sunubus.com', 'www.sunubus.com', '', 'Papa Mor', 'Niane', '2.21773E+11', 1, 'Développement logiciel métier - Applications web - Applications mobile', 0, '', 1, 'Intelligence Artificielle (IA), ', 1, 'E-Payement, Fintech - E-commerce - Smart Cities', 0, '', 'Transport, Logistique'),
(45, 1, 'PME/PMI  ', 'GIE', 'AFRIKA BIO', '2017-09-10', 'Liberté 4 ', 2, '+221781376178/773442970', 'contact@afrikabio.bio', 'Facebook.com/afrikabioofficial', 'Afrika bio séopére dans la distribution de produits bio et naturelles Made in Africa.  - Léidée globale étant de présenter des produits déune qualité égalant les standards internationaux.', 'Matar', 'Coume', '2.21781E+11', 0, '', 0, '', 0, '', 0, '', 0, '', 'Commerce, agroalimentaire, distribution, import & export '),
(46, 1, 'PME/PMI  ', 'GIE', 'NET SOLUTIONS SENEGAL', '2016-05-16', 'KEUR MASSAR', 2, '77 612 49 97', 'netsolutions.sn@gmail.com', 'facebook.com/netsolutions.sn', 'Informatique - Télécommunication - Communication - Génie Civil', 'Mamadou Kabir', 'THIAM', '2.21776E+11', 0, '', 1, 'Composants électroniques et assemblage  - Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires ', 0, '', 1, 'Sécurité, monitoring', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import & export  - Culture, Image, Media ; multimédia, audiovisuel - Aménagement déintérieur et déextérieur  - Média sociaux/Réseaux Sociaux  - Sécurité et Cyber sécurité  - Technologies déentreprises généralistes  - Télécommunications '),
(47, 1, 'STARTUP', '', 'Lifantou SAS', '2017-06-15', '27C Cité Soprim', 2, '2.21784E+11', 'awa.thiam@lifantou.com', 'www.lifantou.com', 'Lifantou est une plateforme d\'accompagnement é la production et é la distribution alimentaire. Nous mettons en relation les producteurs et les cantines gréce é un systéme d\'information géographique basé sur la cartographie et l\'imagerie satellitaire ', 'Awa', 'Thiam', '783749349', 1, 'Développement logiciel métier - Base de données - Applications web', 0, '', 1, 'Imagerie satellitaire et SIG ', 1, 'E-Payement, Fintech - E-commerce - E-agriculture - Nutrition et distribution ', 0, '', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Télécommunications '),
(48, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'MY TERANGA', '2018-02-13', 'Saint-L1s du Sénégal, Ngallele ', 4, '+221771390381', 'ababacarsadikhniang12@gmail.com', 'www.myterangasn.com', 'MY TERANGA est une plateforme de promotion du tourisme culturel et educatif é travers les sévices tels quels: decouvertes des sites historique touristique et culturel en ligne et le service de package en ligne permettant aux populations locales, touristes et visiteurs d\'avoir toutes les commodités nécessaires  (logement, transport, restauration et autres services touristiques) pour découvrir ces sites et patrimoine et vivre une expérience unique.', 'Ababacar Sadikh', 'Niang', '771390381', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Culture, Image, Media ; multimédia, audiovisuel - Autres é préciser'),
(49, 1, 'STARTUP', 'GIE', 'Espaces Topatoo', '2015-10-19', '', 0, '33 897 20 49 / 77 936 81 15 / 77 705 98 69', 'espacestopatoo@gmail.com', '', '', 'Mouhamadou ', 'Gueye', '776095329', 1, 'Programmation informatique', 1, 'Ordinateurs et équipements informatiques', 0, '', 0, '', 0, '', 'Economie Sociale & Solidaire  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Education, Formation, RH, Recherche - Tourisme Culturel '),
(50, 1, 'STARTUP', 'SARL', ' WéTU Digital Lab ', '2017-02-20', 'Liberté 6 Extension Cité JCL Numéro 122 B/ 1er Etage Gauche', 10, '782199410', 'info@watudigital.com', 'www.watudigital.com', 'WéTU Digital Lab est une agence de communication opérationnelle digitale pour le développement rural et le marketing territorial. Nous sommes trés alerte sur les questions de digitalisation et résolument engagés pour relever les défis liés é la formation des jeunes et femmes pour un entrepreneuriat réfléchi en Afrique. -  - Gréce é une maétrise efficiente de la communication socionumérique, Nous vous offrons des solutions innovantes en vue de  Gagner en visibilité é Accroétre léengagement des communautés é Renforcer la crédibilité de vos partenaires .', 'MIKAILA', 'ISSA ABRAMANE', '708028837', 0, '', 0, '', 0, '', 1, 'E-agriculture', 0, '', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Culture, Image, Media ; multimédia, audiovisuel - Marketing et Communication  - Média sociaux/Réseaux Sociaux  - Education, Formation, RH, Recherche'),
(51, 1, 'PME/PMI  ', 'SARL', 'GLOBAL COMPUTER SOLUTIONS SARL', '2000-01-01', 'Sacre coeur II villa Né 8651', 7, '33 869 11 58', 'gcsolutions@gcsolutions.sn', 'www.gcsolutions.sn', 'Systéme et ingénieurie informatique', 'El hadji Mamadou Laye', 'Ndiaye', '778299679', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Composants électroniques et assemblage  - Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires ', 0, '', 1, 'Sécurité, monitoring - E-Payement, Fintech - E-commerce - E-santé - E-agriculture - E-éducation', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Energie et énergies renouvelables - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Marketing et Communication  - Mode, beauté, luxe  - Aménagement déintérieur et déextérieur  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Sécurité et Cyber sécurité  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Industrie, Mines - Technologies déentreprises généralistes  - Télécommunications  - Transport, Logistique'),
(52, 1, 'STARTUP', 'SA', 'CartaLink SASU', '2016-04-28', '252, cité Assemblée Nationale, Dakar, Sénégal', 5, '770983177', 'latyr.senghor@cartalink.com', 'www.cartalink.com', 'Développements d\'applications digitales pour entreprises.', 'Latyr', 'Senghor', '770983177', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile - Monétique, consultance, outsourcing.', 1, 'Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires ', 1, 'big data, ', 1, 'Sécurité, monitoring - E-Payement, Fintech - E-commerce', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Energie et énergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Marketing et Communication  - Mode, beauté, luxe  - Aménagement déintérieur et déextérieur  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Sécurité et Cyber sécurité  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Industrie, Mines - Technologies déentreprises généralistes  - Télécommunications  - Transport, Logistique'),
(53, 1, 'STARTUP', 'SARL', 'BAAMTU', '0000-00-00', 'ouest foire, cité cosapac lot 10', 22, '338206196', 'contact@baamtu.com', 'www.baamtu.com', 'baamtu est dans l\'ingénierie logicielle et dans le big data analytic', 'Mohamed Moustapha ', 'Diouf', '786393838', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 0, '', 1, 'E-santé - E-éducation', 1, 'Télécoms - Hosting, cloud', 'Administration/services publics  - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances  - Restauration, hétellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Technologies déentreprises généralistes  - Télécommunications  - Transport, Logistique'),
(54, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'Agence Consulting-Tech', '2018-01-16', 'Ouakam, en face de la mosquée de la Divinité ', 1, '+2211773344921', 'alamine@africa2dg.org', '', 'Agence Consulting-Tech est une entreprise numérique de services. Nous mettons en place des solutions de collaboration pour faciliter la communication interne et externe de l\'entreprise. - Ensemble consolidons votre croissance avec votre transformation digitale', 'Mouhamadou Lamine Bara ', 'Diagne', '7733449921', 1, 'Applications web', 0, '', 0, '', 0, '', 0, '', 'Marketing et Communication  - Restauration, hétellerie  - Technologies déentreprises généralistes '),
(55, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'APPS 1 GLOBAL', '2018-06-15', 'ROUTE DE NGOR, LES ALMADIES DERRIERE LE RESTAURANT LE KATIA, DAKAR', 5, '33 820 82 40', 'admin@apps1global.com', 'www.apps1global.com', 'Réalisation de plateformes numériques, édition de livres, conseil en communication, publicité.', 'Coumba', 'Ndiaye', '776098160', 1, 'Base de données - Applications web - Applications mobile', 0, '', 0, 'IoT (internet des objets), ', 1, 'E-commerce - E-santé', 1, 'Hosting, cloud', 'Marketing et Communication  - Média sociaux/Réseaux Sociaux '),
(56, 1, 'PME/PMI  ', 'SARL', 'AK-Project', '2014-07-23', '1iere impasse Avenue Bourguiba, Dakar', 15, '33 860 78 72', 'julien@ak-project.com', 'www.ak-project.com', 'Nous travaillons pour tous types d\'acteurs institutionnels, publics et privés. Parmi les nombreuses entreprises qui nous font confiance, nous comptons la plupart des grands comptes présents au Sénégal. -  - Orientés recommandations stratégiques, nous avons une vision globale de la communication digitale de nos clients en assurant des résultats immédiats et des bénéfices sur le long terme. Nous internalisons également un grand nombre de fonctions pour une meilleure réactivité face é nos clients. Création graphique, Développement, Rédactionnel, Gestion de projet sont é la base note savoir.', 'Julien', 'MALLE', '778193890', 0, '', 0, '', 0, '', 0, '', 0, '', 'Marketing et Communication '),
(57, 1, 'PME/PMI  ', 'SA', 'SOLID', '2005-12-19', '4 Cite Comico 3 VDN', 19, '776399565', 'solid@solid.sn', 'www.solid.sn', '', 'Moustapha', 'DIOP', '776399565', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 1, 'big data,  - Distribution de musique Digitale en ligne', 1, 'Sécurité, monitoring - E-Payement, Fintech - E-commerce', 1, 'Hosting, cloud', 'Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Technologies déentreprises généralistes  - Télécommunications '),
(58, 1, 'PME/PMI  ', 'SARL', 'PROSE', '2010-06-17', '4250 SICAP Amitie 3 Dakar', 8, '338651150', 'prose@prose.sn', 'www.prose.sn', 'Ingénierie Logicielle', 'Moustapha', 'DIOUF', '776470760', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 0, '', 1, 'E-Payement, Fintech - E-santé - E-agriculture', 0, '', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export '),
(59, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'DIAMALAYE SERVICES TELECOMS INFORMATIQUE', '2016-01-01', 'GUEDIAWAYE BAYE LAYE WAKHINANE NIMZAT', 1, '764630163', 'diamalayeservice@zoho.com', '', 'prestation de service , commerce marchandise divers import export', 'ABDALLAH ', 'NDIAYE', '', 1, '', 1, 'Ordinateurs et équipements informatiques', 0, '', 0, '', 0, '', 'Santé, bien é étre  - Emploi, RH, Services é la personne '),
(60, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'THIAM INFORMATIQUE', '2010-01-15', 'quartier pont', 4, '77 243 63 72', 'adamahiam21@gmail.com', '', 'Installation systéme Windows-Mac -linux Ubuntu etc... et réparation imprimante et photocopie. Dépannage électronique des carte méres et céblage réseau internet des caméra', 'Adama Galobel', 'THIAM', '772436372', 1, 'Développement logiciel métier - Base de données', 1, 'Composants électroniques et assemblage  - Ordinateurs et équipements informatiques', 0, '', 1, 'E-commerce', 1, 'Services réseaux', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import & export  - Sécurité et Cyber sécurité  - Emploi, RH, Services é la personne  - Technologies déentreprises généralistes '),
(61, 1, 'PME/PMI  ', 'SARL', 'JALAL ENTREPRISE SERVICES', '2011-10-13', 'LIBERTE 6 EXTENSION RUE HLM GRAND YOFF', 5, '338276350', 'jalalsarl@orange.sn', 'www.jalalservices.sn', 'Prestations de services', 'Abdourahmane', 'Sall', '777153422', 1, 'Applications web', 1, 'Composants électroniques et assemblage ', 1, 'big data, ', 1, 'Sécurité, monitoring', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Commerce, agroalimentaire, distribution, import & export  - Electricité, Froid, Informatique, Promberie, BTP'),
(62, 1, 'PME/PMI  ', 'SARL', 'Finance Expertise Technologie', '2009-01-01', 'Mermose Comico Né60', 30, '338606760', 'manager@finetechgroupe.com', 'www.finetechgroupe.com', 'Société informatique, fournisseur des produits et services informatiques et télécommunications. ', 'Mamadou ', 'Diop', '338606760', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Matériels Telecom', 0, '', 0, '', 1, 'Télécoms', 'Administration/services publics  - Banque, finance, assurances '),
(63, 1, 'PME/PMI  ', 'SARL', 'SYSCOM TECHNOLOGY', '2008-08-14', 'CITE KEUR GORGUI LOT 60', 10, '338670577', 'direction@syscom-technology.com', 'www.syscom-technology.com', 'Intégrateur de solutions informatique, Impression numérique', 'Amadou Gueye', 'Cissoko', '774347718', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Ordinateurs et équipements informatiques', 0, '', 1, 'Sécurité, monitoring', 1, 'Services réseaux - Hosting, cloud', 'Administration/services publics  - Marketing et Communication  - Technologies déentreprises généralistes '),
(64, 1, 'STARTUP', 'SA', 'AYKOUM GROUP SAS', '2017-01-01', '3 RUE BERANGER X FERRAUD DAKAR PLATEAU', 1, '781540519', 'aykoumgroup@gmail.com', 'www.batipay.com', 'Ecommerce /marketplace: achat, vente et payement de produits/ services pour l\'habitat', 'Nouha', 'Sagna', '766490856', 0, '', 0, '', 0, '', 1, 'E-Payement, Fintech - E-commerce', 0, '', 'Commerce, agroalimentaire, distribution, import & export  - Marketing et Communication  - Média sociaux/Réseaux Sociaux '),
(65, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'DIA PRO MEDIA', '2016-01-17', 'Thies', 1, '775733879', 'diaproibou@gmail.com', 'Page Facebook / DIA PRO MEDIA', 'DIA PRO MEDIA est une structure en multimédia qui développe l\'audiovisuel ,le webdesign  et le web master', 'Ibrahima', 'DIA', '', 0, '', 0, '', 0, '', 0, '', 0, '', 'Culture, Image, Media ; multimédia, audiovisuel'),
(66, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Urban News SENEGAL', '2019-06-24', 'Hann Bel-air', 7, '77 302 59 47', 'urbannewssn@gmail.com', 'urban-news.sn', 'Premiére plateforme de presse en ligne dédiée aux cultures urbaines du sénégal.', 'Lamine', 'SOW', '781580986', 1, 'Applications web', 0, '', 1, 'Actualités, fournir des informations ', 1, 'Musical', 1, 'Internet', 'Culture, Image, Media ; multimédia, audiovisuel - Média sociaux/Réseaux Sociaux '),
(67, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'STAR BUSINESS', '2015-01-01', 'Diamaguene dagana', 3, '779001139', 'dgstarbusiness@gmail.com', '', 'Maintenance informatique mécanographe électromécanique céligraphe transfert d\'argent commerce prestation de services ', 'Abdou ', 'DIEYE', '779001139', 1, 'Développement logiciel métier', 1, 'Composants électroniques et assemblage  - Ordinateurs et équipements informatiques', 1, 'Animation 3D,                                ', 1, 'E-Payement, Fintech', 1, 'Services réseaux', 'Energie et énergies renouvelables - Culture, Image, Media ; multimédia, audiovisuel - Marketing et Communication  - Média sociaux/Réseaux Sociaux  - Technologies déentreprises généralistes ');
INSERT INTO `listestartups` (`id`, `ownerID`, `type`, `statut_juridique`, `denomination`, `date_creation`, `adresse`, `effectif`, `telephone_un`, `email`, `site_web`, `description`, `prenom`, `nom`, `telephone_deux`, `software`, `sous_domaine_soft`, `hardware`, `sous_domaine_hard`, `ict_advance`, `sous_domaine_ict_advance`, `ict_service`, `sous_domaine_ict_service`, `ict_network`, `sous_domaine_ict_network`, `secteur`) VALUES
(68, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'GASBA', '2014-02-01', 'Mbodiéne Podor', 2, '782732508', 'amadou78seck@gmail.com', '', 'Multiservices: photocopie, tirage, traitement, cyber connexion résean interne, cours informatique (word, excel, power point , conception de site web), confection de cartes: mariage, visite, membre', 'Amadou', 'SECK', '782732508', 1, 'Applications web', 1, 'Composants électroniques et assemblage  - Ordinateurs et équipements informatiques', 0, '', 0, '', 1, 'Services réseaux', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Mode, beauté, luxe  - Média sociaux/Réseaux Sociaux  - Education, Formation, RH, Recherche'),
(69, 1, 'PME/PMI  ', 'GIE', 'Xuuli Beut', '2013-01-01', 'Medina course  sor saint l1s du Sénégal', 5, '764809582', 'bgtalle@gmail.com', '', 'Nous avons la serigraphie,l\'infographie et decoration-pub. Notre activités consiste é confectionner des logos, reproduire des images,logos et textes sur les tee shirt, casquettes, lacoste etc. Tirage affiches, bandoroles enseignes et table de direction.', 'Allé', 'MBAYE', '774809582', 0, '', 0, '', 0, '', 0, '', 0, '', 'sérigaphe'),
(70, 1, 'PME/PMI  ', 'SA', 'NEDGESYSTEMS', '2018-01-05', 'Sacré céur keur gorgui', 15, '338691413', 'contact@nedgesys.com', 'www.nedgesys.com', 'Société d\'intégration de services informatiques : installation réseaux informatiques,ToIP,WIFI,WAN, sécurisation Réseaux informatiques, - Audit, Formation,Cablage informatique et électrique ', 'Mamadou', 'Thiam', '338691412', 1, 'Installation Application metier', 1, 'Ordinateurs et équipements informatiques', 0, '', 1, 'Sécurité, monitoring', 1, 'Services réseaux', 'Administration/services publics  - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Energie et énergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Marketing et Communication  - Mode, beauté, luxe  - Aménagement déintérieur et déextérieur  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Sécurité et Cyber sécurité  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Industrie, Mines - Technologies déentreprises généralistes  - T&e'),
(71, 1, 'PME/PMI  ', 'SARL', 'Pléxus Studios Sénégal', '2018-01-05', 'Hann Bel air / Yarakh', 10, '78 158 09 86', 'plexusstudiossenegal@gmail.com', '', 'Agence de communication', 'Lamine', 'SOW', '781580986', 0, '', 0, '', 1, 'Création de contenus multimédias', 0, 'Autres (é préciser)', 0, '', 'Culture, Image, Media ; multimédia, audiovisuel - Marketing et Communication  - Média sociaux/Réseaux Sociaux '),
(72, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Astou Dieng', '2016-09-30', 'Thiaroye Azur Mbattal', 0, '774882671', 'diengastou14@gmail.com', 'www.cad-communication.com', 'Développement de sites , applications mobiles - Commnunity management  - Campagnes digitales  - Creations graphiques supports de communication print .', 'Astou', 'Dieng', '', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import & export  - Marketing et Communication  - Mode, beauté, luxe  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie '),
(73, 1, 'STARTUP', 'GIE', 'Start-It Up(Education Numérique pour tous)', '2018-01-04', 'Ex Terrain Foyer Rocade Fann Bel Air, BP 10 000 Dakar Liberté SENEGAL', 10, '780132980', 'startitup221@gmail.com', 'https://www.facebook.com/madisn221/', 'Start-It Up est un programme déinitition aux technologies de léinformation et de la communication. - A travers des ateliers de formation nous essayons de sensibiliser la population sur les enjeux du numérique et pour une utilisation sure déInternet', 'Abdourahmane', 'Traoré', '780132980', 0, '', 0, '', 0, '', 1, 'Education Numérique', 0, '', 'Culture, Image, Media ; multimédia, audiovisuel - Média sociaux/Réseaux Sociaux  - Sécurité et Cyber sécurité  - Sensibilisation Numérique'),
(74, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'AyudaFund ', '2019-06-07', 'Dakar-Sénégal ', 2, '78 103 85 93', 'oumouwone@ayudafund.com', 'www.ayudafund.com', 'Donnez lï¿½opportunitï¿½ aux femmes foyers vulnÃ©rables , retraitï¿½s vulnï¿½rables et personnes handicapï¿½es dï¿½avoir une vie descente en investissant votre temps et votre argent dans leurs activitï¿½s gï¿½nï¿½ratrices de revenus.', 'Oumouhane Saoudatou ', 'Wone', '781038593', 1, 'Applications web', 1, 'Ordinateurs et équipements informatiques', 0, '', 0, '', 0, '', 'Economie Sociale &amp; Solidaire '),
(75, 1, 'STARTUP', 'GIE', 'SENEBOT', '2018-06-13', 'Mermoz- Dakar', 10, '781582233', 'contact@senebot.com', 'www.senebot.com', 'une Startup qui evolue dans le milieu de la robotique en realisant des projets et qui forme la jeune generation a cela', 'Abdoul Aziz Sy', 'Ndiaye', '771265395', 0, '', 0, '', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - Drone, robotique', 0, '', 0, '', 'Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Education, Formation, RH, Recherche - Technologies déentreprises généralistes  - Robotique'),
(76, 1, 'PME/PMI  ', 'SARL', 'ATELIER DE MAINTENANCE AUTO INDUSTRIEL INSTALLATIONS MICRO IRRIGATIONS ', '2005-01-10', 'Route du Frond de Terre X Rue A', 5, '775218517', 'frontamai@hotmail.fr', '', 'Aménagement agricole(irrigation en goutte é goutte addiction d\'eau). - Terrassement installation forage systéme automatisation agricole installation serres.', 'Sidy Lamine', 'Diarra', '775218517', 0, '', 0, '', 0, '', 0, '', 0, '', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export '),
(77, 1, 'PME/PMI  ', 'SARL', 'GOLDEN EYES AFRICA', '2007-01-01', 'Liberté extension', 2, '338670970', 'golden-eyes@orange.sn', '', 'société d\'intégrateur de services informatiques ', 'Amine', 'KEBE', '338670970', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile - Autres sous domaines', 1, 'Terminaux mobiles et accessoires ', 0, '', 0, '', 1, 'Services réseaux - Hosting, cloud', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances  - Culture, Image, Media ; multimédia, audiovisuel - Marketing et Communication  - Aménagement déintérieur et déextérieur  - Restauration, hétellerie  - Education, Formation, RH, Recherche'),
(78, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Njureel', '2019-03-26', 'hann Maristes cité Elisabeth Diouf n*12 BIS/', 7, '+221774183376', 'njureelservices@gmail.com', 'www.njureel.com ( en construction )', 'Recherches et développement de solutions e-santé: developpemnt d\'un systéme de télémédicine pour les femmes enceintes en milieu rural', 'Awa', 'Ndiaye', '2.21774E+11', 1, 'Base de données - Applications web - Applications mobile', 0, '', 0, '', 1, 'E-Payement, Fintech - E-santé', 0, '', 'Santé, bien é étre  - Economie Sociale & Solidaire '),
(79, 1, 'PME/PMI  ', 'GIE', 'KAYELEEN INFORMATIQUE', '2015-01-01', 'ZIGUINCHOR', 7, '775447014', 'gerome.sambou@gmail.com', '', 'Formation en informatique et déploiement de services informatique', 'Gerome ', 'Sambou', '775447214', 0, '', 0, 'Ordinateurs et équipements informatiques', 0, '', 0, '', 0, '', 'Administration/services publics  - Education, Formation, RH, Recherche'),
(80, 1, 'STARTUP', 'SUARL', 'Black Star Technologies', '2017-06-07', 'Lot 139; Sicap Foire, Dakar - Sénégal', 5, '2.21339E+11', 'contact@blackstar-tech.com', 'www.blackstar-tech.com', 'Black Star Technologies est une société de services numériques spécialisée dans le développement déapplications et léintégration de solutions principalement dans les métiers et domaines déactivité suivants:  - é	Biométrie et cartes é puce - é	Centres déappels, IVRs, SMS - é	Monétique et solutions de paiement - Léatout majeur de Black Star Technologies est sa capacité é combiner ces différentes technologies pour fournir une solution globale unique aux problématiques spécifiques de ses clients.', 'Mamadou Lamine', 'KA', '2.21776E+11', 1, 'Développement logiciel métier - Applications web - Applications mobile', 1, 'Lecteurs et imprimantes é cartes, embosseuses, éuipements biométriques', 0, '', 1, 'E-Payement, Fintech', 1, 'Centres d\'appels, Plateformes SMS, Serveurs Vocaux, IPBX', 'Administration/services publics  - Banque, finance, assurances  - Technologies déentreprises généralistes  - Télécommunications '),
(81, 1, 'PME/PMI  ', 'SARL', 'Soyere Consulting', '2004-01-01', '115Rue Carnot Dakar', 5, '338218749', 'contact@soyere.org', 'www.soyere.org', '', 'Nicolas', 'SOYERE', '338218749', 1, 'Développement logiciel métier - Base de données', 1, 'Ordinateurs et équipements informatiques', 0, '', 0, '', 0, '', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances  - Industrie, Mines - Technologies déentreprises généralistes  - Transport, Logistique'),
(82, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Global Business Solutions', '2017-03-27', 'Mbour/Sénégal', 4, '777018218', 'oussen91@gmail.com', '', 'Servicesinformatique : formation des éléves de la primaire au lycée', 'Ousmane ', 'SY', '', 0, '', 1, 'Ordinateurs et équipements informatiques', 1, 'IoT (internet des objets), ', 0, '', 1, 'Services réseaux', 'Agriculture, élevage ; environnement, péche - Transport, Logistique'),
(83, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'INTECH', '2012-07-02', 'Parcelles Assainies U8 Dakar', 1, '777617368', 'fatou.diaoune@agence-intech.com', 'www.agence-intech.com', 'Créaction de site web, Application web, Intranet, Référencement web, Intégration de solution web, Formation, ...', 'Fatou', 'DIAOUNE', '777617368', 1, 'Développement logiciel métier - Base de données - Applications web - Intégration, référencement web, formation', 0, '', 0, '', 1, 'E-commerce - E-santé', 1, 'Hosting, cloud', 'Administration/services publics  - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Energie et énergies renouvelables - Marketing et Communication  - Mode, beauté, luxe  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie  - Education, Formation, RH, Recherche - Industrie, Mines - Technologies déentreprises généralistes '),
(84, 1, 'PME/PMI  ', 'SUARL', 'WEST AFRICAN NETWORKFOR GLOBAL ONLINE (WANGO)', '2015-01-01', 'Hlm grand yoff Né443- immeuble Tabara NGOM 3ieme étage, Bureau Cé', 5, '33 867 72 05  76 645 75 23', 'contact@wango.sn', 'www.wango.sn', 'La consultation dans les réseaux et les systémes - L\'audit et diagnostic des systémes informatiques  - Toutes activités d\'hébergementde données ,de services mangés et de cloud computing - Le développement de logiciel, l\'étude et le conseil en systéme information  - L\'audit de sécurité et des tests d\'instrusion des systémes informatiques et réseaux ; l\'étude , la conception, le suivi et la réalisation d\'architecture réseaux et systémes informatiques, l\'animation de séminaires et de séances de  formation dans le domaine de l\'informatique , des réseaux et des télécommunications', 'Alioune Badara', 'DIOP', '777636445', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 1, 'Ordinateurs et équipements informatiques - Terminaux mobiles et accessoires ', 1, 'Intelligence Artificielle (IA),  - big data, ', 1, 'Sécurité, monitoring - E-Payement, Fintech - E-santé', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Banque, finance, assurances  - Marketing et Communication  - Restauration, hétellerie  - Sécurité et Cyber sécurité  - Industrie, Mines - Technologies déentreprises généralistes  - Télécommunications '),
(85, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'BONJOUR SENEGAL, BONJOUR SUNUGAL SERVICES, ', '2018-04-09', 'SICAP LIBERTE 5 VILLA Né5351/B Dakar, Sénégal', 3, '2.21782E+11', 'contact@bonjoursenegal.com', 'https://www.bonjoursenegal.com', 'BONJOUR SENEGAL est une plateforme digitale dédiée é la promotion de la destination SENEGAL.  - BONJOUR SENEGAL a pour ambition premiére de développer lééconomie locale é travers le tourisme en permettant aux sénégalais de (re) découvrir ce magnifique pays !  - Nous souhaitons connecter voyageurs et acteurs locaux du Tourisme car, é l\'ére oé tout se passe sur Internet, trés peu déacteurs locaux sénégalais (hétels, musées, maison déhétes, activités touristiquesé) sont présents sur le web.', 'Ndéye Aminata ', 'Voyel', '2.21782E+11', 1, 'Applications web - Applications mobile', 0, '', 0, '', 1, 'E-Tourisme', 0, '', 'Economie Sociale & Solidaire  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Média sociaux/Réseaux Sociaux  - Restauration, hétellerie '),
(86, 1, 'PME/PMI  ', 'SA', 'MAYI Senegal SAS', '2018-05-16', '07 rue jean mermoz, Dakar, Plateau', 27, '', 'adam.cox@miya-africa.com', 'www.miya-africa.com', 'Purification, Embouteillage & Distribution d\'Eau', 'Adam', 'Cox', '771446129', 0, '', 0, '', 0, '', 0, '', 0, '', ''),
(87, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'PrestaDak', '2015-01-14', 'Sacre coeur 3', 3, '764596001', 'contact@prestadak.com', 'http://prestadak.com', 'Agence web spécialisée dans le développement de plateforme e-commerce, site internet et apllication mobile', 'Mohamadou', 'Ndiaye', '779326509', 1, 'Développement logiciel métier - Base de données - Applications web - Applications mobile', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Culture, Image, Media ; multimédia, audiovisuel - Sport, Jeux vidéo, Loisirs & Tourisme  - Marketing et Communication  - Mode, beauté, luxe  - Restauration, hétellerie  - Education, Formation, RH, Recherche - Industrie, Mines'),
(88, 1, 'STARTUP', 'SUARL', 'SOXLLA.COM SUARL', '2016-03-18', 'Sacré Coeur 2, Immeuble Sokhna Astou LO - Bloac A', 19, '338643332', 'contact@soxlla.com', 'www.yobuma.com', 'SOXLLA a un produit nommé \"YOBUMA\" qui est une solution de réservation de billets de bus interurbains. ', 'Sankoung', 'AIDARA', '774120753', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Transport, Logistique'),
(89, 1, 'STARTUP', 'SARL', 'Niokobok', '2012-01-01', 'sud foire villa 142', 9, '771154233', 'team@niokobok.com', 'www.niokobok.com', '', 'Laurant', 'Liautaud', '771987964', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Commerce, agroalimentaire, distribution, import & export '),
(90, 1, 'PME/PMI  ', 'SARL', 'SESAM INFORMATICS', '2006-11-30', '28 CITE TEYLIUM VDN BP 11764 DAKAR PEYTAVIN', 30, '338675230', 'contact@sesam.sn', 'www.sesam.sn', 'INTEGRATION DE SOLUTIONS INFORMATIQUES', 'Meuleye', 'MBOUP', '776373772', 0, '', 1, 'MATERIEL DE TELECOMMUNICATION RESEAUX ET SECURITE', 0, '', 0, '', 1, 'Télécoms - Services réseaux - Hosting, cloud', 'Administration/services publics  - Banque, finance, assurances  - Sécurité et Cyber sécurité  - Télécommunications '),
(91, 1, '', 'SARL', 'ANDEL-GHANDI', '2017-01-12', '4 CITE MAMA RHANE OUEST FOIRE', 1, '775369263/778119786', 'andelghandi@gmail.com', '', 'consultant/conseiller en business plan/GAR,gestion/RH - JE fais des études de projets pour les personnes ayant une idée é concrétiser et ne savent pas comment la matérialiser ou qui cherchent un financement  ', 'ROBERT ANDEL', 'SARR', '775369263', 0, '', 0, '', 0, '', 0, '', 0, '', 'Agriculture, élevage ; environnement, péche - Commerce, agroalimentaire, distribution, import & export  - Restauration, hétellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services é la personne  - Transport, Logistique - POUR AUTRES LE BATIMENT '),
(93, 1, 'STARTUP', 'SARL', 'DARAL TECHNOLOGIES', '2015-01-01', 'PARCELLES ASSAINIES U 3 VILLA 416', 50, '771026094', 'sow.amadou78@yahoo.fr', 'daralserver.cloudapp.net', 'Besoins  des  éleveurs : - Problématiques é résoudre. - Dans le cadre de la réduction de la pauvreté et la sauvegarde des acquis des éleveurs ; nous sommes préoccupés é faire intervenir léoutil informatique au service du monde rural. - On sait que dans le monde actuel toute activité de développement peut profiter des acquis de la nouvelle technologie. - Donc léélevage doit prendre sa place dans le systéme informatique pour apporter des solutions aux fléaux qui habitent ce secteur déactivités notamment : - - les épizooties qui font des ravages pour le cheptel en général partout en Afrique et ces dégéts s', 'AMADOU', 'SOW', '771026094', 1, 'Base de données - Applications web - Applications mobile', 0, '', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA), ', 1, 'E-commerce - E-santé - E-agriculture', 1, 'Services réseaux', 'Administration/services publics  - Agriculture, élevage ; environnement, péche - Santé, bien é étre  - Commerce, agroalimentaire, distribution, import & export  - Economie Sociale & Solidaire  - Média sociaux/Réseaux Sociaux '),
(94, 1, 'PME/PMI  ', 'SA', 'SOCITECH GUINNEE', '2012-06-21', 'KIPE centre emetteur, commune de ratoma', 8, '669390006', 'guinee@socitech.com', 'www.socitech.com', 'Intégrateurs de solutions informatique (Systéme,réseau,sécurité) - Dématérialisation et Archivage électronique de documents - Formation et certification en informatique - Accompagnement et service aprés vente - Fourniture de matériel informatique et onduleurs  - Cablage électrique,Informatique', 'Jean-Marc BEDJE', 'KOFIA', '669390007', 1, 'Base de données', 1, 'Ordinateurs et équipements informatiques', 0, '', 1, 'Sécurité, monitoring', 1, 'Télécoms', 'Administration/services publics  - Banque, finance, assurances  - Industrie, Mines - Télécommunications '),
(96, 13, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'MEDINA TECH', '2019-09-02', 'DAKAR', 1, '772257744', 'fila@gmail.com', 'neant', 'creation de logiciel', 'marietou', 'dia', '', 0, '', 0, '', 0, '', 0, '', 0, '', 'soft'),
(100, 1, '', 'ENTREPRISE INDIVIDUELLE', 'Niang&amp;Co', '2005-02-02', 'rue de reims', 4, '784514545', 'admin@gmail.com', 'www.wango.sn', 'ig', 'uyuy', 'yguyg', '', 0, '', 0, '', 0, '', 0, '', 0, '', 'uyfuy');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `listestartups`
--
ALTER TABLE `listestartups`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_ownerId` (`ownerID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `listestartups`
--
ALTER TABLE `listestartups`
  MODIFY `id` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `listestartups`
--
ALTER TABLE `listestartups`
  ADD CONSTRAINT `fk_ownerId` FOREIGN KEY (`ownerID`) REFERENCES `utilisateurs` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
