-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 08, 2019 at 12:45 AM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.3.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `startups`
--

-- --------------------------------------------------------

--
-- Table structure for table `listestartups`
--

CREATE TABLE `listestartups` (
  `id` int(8) NOT NULL,
  `ownerID` int(8) NOT NULL DEFAULT 1,
  `type` varchar(255) NOT NULL,
  `statut_juridique` varchar(255) NOT NULL,
  `denomination` varchar(255) NOT NULL,
  `date_creation` date NOT NULL,
  `adresse` varchar(255) NOT NULL,
  `effectif` int(8) NOT NULL,
  `telephone_un` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `site_web` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `prenom` varchar(255) NOT NULL,
  `nom` varchar(255) NOT NULL,
  `telephone_deux` varchar(255) NOT NULL,
  `software` int(1) NOT NULL,
  `sous_domaine_soft` text NOT NULL,
  `hardware` int(1) NOT NULL,
  `sous_domaine_hard` text NOT NULL,
  `ict_advance` int(1) NOT NULL,
  `sous_domaine_ict_advance` text NOT NULL,
  `ict_service` int(1) NOT NULL,
  `sous_domaine_ict_service` text NOT NULL,
  `ict_network` int(1) NOT NULL,
  `sous_domaine_ict_network` text NOT NULL,
  `secteur` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `listestartups`
--

INSERT INTO `listestartups` (`id`, `ownerID`, `type`, `statut_juridique`, `denomination`, `date_creation`, `adresse`, `effectif`, `telephone_un`, `email`, `site_web`, `description`, `prenom`, `nom`, `telephone_deux`, `software`, `sous_domaine_soft`, `hardware`, `sous_domaine_hard`, `ict_advance`, `sous_domaine_ict_advance`, `ict_service`, `sous_domaine_ict_service`, `ict_network`, `sous_domaine_ict_network`, `secteur`) VALUES
(1, 1, 'STARTUP', 'SARL', 'Keydjune &amp; AssociÃ©s', '2016-06-17', 'Ouest foire lot 8 villa 67', 10, '338202832', 'keydjune@gmail.com', 'www.keydjuneholding.com', 'IT business,montique et finance.', 'Christian', 'Pape samba gueye', '774241502', 1, 'DÃ©veloppement logiciel mÃ©tier - Applications web - Applications mobile', 1, 'Terminaux mobiles et accessoires  - Ã©quipements monÃ©tique', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - big data,  - Drone, robotique - AR/VR (rÃ©alitÃ©s augmentÃ©es/rÃ©alitÃ©s virtuelles), - Blockchain', 1, 'E-Payement, Fintech - E-commerce - E-tourisme', 1, 'Services rÃ©seaux - Hosting, cloud', 'Economie Sociale &amp; Solidaire  - Banque, finance, assurances  - Sport, Jeux vidÃ©o, Loisirs &amp; Tourisme  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Technologies d entreprises -gÃ©nÃ©ralistes  - Transport, Logistique - Digital Culture et agilitÃ©'),
(2, 1, 'STARTUP', 'GIE', 'NIFRITECH', '2017-11-14', 'Dakar Fann Bel Air', 0, '+221 78 420 37 94', 'anicet.kiemde@nifritech.com', 'www.nifritech.com', 'Formation et coaching certification  - IngÃ©nierie fibre optique et rÃ©seaux  - DÃ©veloppement d\'application - SÃ©curitÃ© des SI - IOT', 'Sountongnoma Martial Anicet', 'KIEMDE', '', 1, 'Applications web - Applications mobile', 1, 'Composants Ã©lectroniques et assemblage ', 1, 'IoT (internet des objets),  - Drone, robotique', 1, 'SÃ©curitÃ©, monitoring', 1, 'TÃ©lÃ©coms - Services rÃ©seaux', 'Agriculture, Ã©levage ; environnement, pÃ¨che - SÃ©curitÃ© et Cyber sÃ©curitÃ© - Education, Formation, RH, Recherche - TÃ©lÃ©communications '),
(3, 1, 'STARTUP', 'SARL', 'linkmoney &amp; ntic', '2018-01-25', 'mermoz 155 x VDN', 5, '778177919', 'christian.linkmoneyntic@gmail.com', 'www.linkmoneyntic.com', 'reprÃ©sentant exclusif de grandes industries de terminaux MPOS,ATM-Machine, Bornes, Compteuses Trieuses de billets,Agence Digitale, avec les Tellers machines, Gateway et Swift. - Nous offrons Ã  nos partenaires toutes les solutions monÃ©tiques HardWare et SoftWare.', 'christian', 'lengha lengha', '774241502', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'Composants Ã©lectroniques et assemblage  - Ordinateurs et Ã©quipements informatiques - Autres Ã©quipements', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - big data,  - Drone, robotique - AR/VR (rÃ©alitÃ©s augmentÃ©es/rÃ©alitÃ©s virtuelles),', 1, 'SÃ©curitÃ©, monitoring - E-Payement, Fintech - E-commerce - E-Ã©ducation', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp; export  - Economie Sociale &amp; Solidaire  - Banque, finance, assurances  - Sport, Jeux vidï¿½o, Loisirs &amp; Tourisme  - Marketing et Communication  - Mï¿½dia sociaux/Rï¿½seaux Sociaux  - Sï¿½curitï¿½ et Cyber sï¿½curitï¿½  - Technologies dï¿½entreprises gï¿½nï¿½ralistes  - Tï¿½lï¿½communications '),
(4, 1, 'STARTUP', 'SARL', 'Startup Xayma Mbay', '2018-05-16', 'UniversitÃ© Gaston Berger Saint-L1s du SENEGAL', 3, '774594319', 'assanemoussa24@gmail.com', '', 'Xayma Mbay est une plateforme collaborative qui interconnecte les acteurs de l\'Ã©cosystÃ©me agricole.', 'ASSANE', 'GUEYE', '774594319', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires ', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - big data, ', 1, 'SÃ©curitÃ©, monitoring - E-Payement, Fintech - E-commerce - E-agriculture - E-Ã©ducation', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Agriculture, Ã©levage ; environnement, pÃ©che - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(5, 1, 'STARTUP', 'SARL', 'SUGU SAS', '2017-03-17', 'sacre coeur 3 villa 10053', 21, '338592581', 'yam@1carry.com', 'WWW.1CARRY.COM', 'entreprise de logistique crossboarder spÃ©cialisÃ© sur le e-commerce', 'oumar', 'yam', '771178595', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Commerce, agroalimentaire, distribution, import &amp;export  - Transport, Logistique'),
(6, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'PratiSIG Consulting ', '2017-09-01', '125 B,  CitÃ© Soprim, Dakar', 5, '771270387', 'pratisig.consulting@gmail.com', 'www.pratisig.tk', 'Offre de formations en GÃ©omatique, Prestation de services en SIG,  DÃ©veloppement local et sondage', 'Youssoupha ', 'MBODJI ', '771270387', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Education, Formation, RH, Recherche'),
(7, 1, 'STARTUP', 'SARL', 'IPANEL SARL', '2016-01-01', '', 0, '773472497', 'moulaye.aidara@ipanel-education.com', 'www.ipanel-education.com', 'LÃ©objectif de lÃ©Institut Panafricain dÃ©Enseignement en Ligne Ã© IPANEL est dÃ©apporter une contribution dans la promotion et le dÃ©veloppement de la formation Ã© distance. Il sÃ©agit dÃ©aider Ã© la dÃ©finition et Ã© lÃ©amÃ©lioration des programmes et projets de formation et le renforcement des capacitÃ©s pour un meilleur dÃ©veloppement national de la formation Ã© distance. La dÃ©marche consiste Ã© identifier et Ã© prendre en compte tous les aspects humains, matÃ©riels, techniques et financiers afin dÃ©adopter les meilleures pratiques possibles tout en dÃ©gageant des leviers de rentabilitÃ© Ã©conomique.', 'Moulaye', 'AIDARA', '773472497', 0, '', 0, '', 0, '', 1, 'E-Ã©ducation', 0, '', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - Energie et Ã©nergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Marketing et Communication  - Mode, beautÃ©, luxe  - AmÃ©nagement dÃ©intÃ©rieur et dÃ©extÃ©rieur  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Industrie, Mines - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications  - Transport, Logistique'),
(8, 1, 'STARTUP', 'SUARL', 'SYSLAB', '2018-08-17', 'Ngor Virage Lot NÃ© 56', 8, '339593258', 'contact@syslab.sn', 'www.syslab.sn', 'Agence digitale - StratÃ©gies d\'entreprise', 'Ngagne', 'Top', '773541553', 1, 'Applications web - Applications mobile', 1, 'SignalÃ©tique digitale', 1, 'Animation 3D,                                 - Intelligence Artificielle (IA),  - Drone, robotique - AR/VR (rÃ©alitÃ©s augmentÃ©es/rÃ©alitÃ©s virtuelles),', 1, 'E-Payement, Fintech - E-commerce - E-agriculture - E-Ã©ducation', 1, 'TÃ©lÃ©coms - Hosting, cloud', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Energie et Ã©nergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Marketing et Communication  - Mode, beautÃ©, luxe  - AmÃ©nagement dÃ©intÃ©rieur et dÃ©extÃ©rieur  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications  - Transport, Logistique'),
(9, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'EXPERT ACTU', '2017-02-07', 'Dakar, SÃ©nÃ©gal SacrÃ© coeur 2', 5, '00221 77 342 45 15 / 00 221 77 839 9437', 'expertactu.officiel@gmail.com', 'https://www.facebook.com/expertactu/', 'EXPERT ACTU, plateforme web media, qui traite l\'information internationale, d\'actualitÃ© mondiale, dont l\'ambition est de porter la voix de l\'Afrique hors du continent, et tÃ©moigner les opportunitÃ©s que peut peut offrir internet de nos jours.', 'Abd-El Senguel Florey ', 'MAFOULA', '2.21773E+11', 1, 'Applications web - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Administration/services publics  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux '),
(10, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'actuvision.com', '2018-01-01', 'RUE 12 X AVENUE BOURGUIBA', 0, '+221773129258', 'actuvisiontv@gmail.com', 'http://actuvision.com/', 'ActuvisionTV  WWW.ACTUVISION.COM - Un Clin d\'oeil Sur l\'Actu  - sit information national international ', 'mohamed lamine ', 'fall', '773129258', 1, 'Base de donnÃ©es', 0, '', 0, '', 0, '', 1, 'Services rÃ©seaux', 'MÃ©dia sociaux/RÃ©seaux Sociaux '),
(11, 1, 'STARTUP', 'SUARL', 'Demarch', '2017-10-20', 'Keur massar sur la route du lac rose', 9, '338970846', 'fbdiop@demarch.sn', 'www.demarch.sn', 'DÃ©matÃ©rialisation, archivage numÃ©rique, Ã©dition numÃ©rique, traitement de donnÃ©es', 'Fatou Bintou', 'DIOP', '778639264', 1, 'Production', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 1, 'DÃ©matÃ©rialisation', 0, '', 'Administration/services publics  - Edition'),
(12, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'innov\'digital', '2018-11-13', '3, Rue BÃ©ranger FÃ©raud', 10, '+221781735479', 'fayeabdoulaye45@gmail.com', 'www.innovdigital.sn', 'Innov digital est une startup de communication digitale spÃ©cialisÃ©e dans le dÃ©veloppment de logiciels, de l\'infographie, du web-marketing et du dÃ©veloppement des solutions monÃ©tiques', 'Abdoulaye', 'Faye', '2.21782E+11', 1, 'DÃ©veloppement logiciel mÃ©tier - Applications web - Applications mobile', 0, '', 1, 'IoT (internet des objets),  - AR/VR (rÃ©alitÃ©s augmentÃ©es/rÃ©alitÃ©s virtuelles),', 1, 'E-Payement, Fintech', 1, 'Services rÃ©seaux', 'Administration/services publics  - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(13, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'JOBTEL', '2015-06-16', 'point E rue A x 2', 6, '338256110', 'contact@jobtel.sn', 'www.jobtel.sn', 'JOBÃ©tel SÃ©nÃ©gal un nouveau produit qui consiste Ã© faciliter le quotidien des demandeurs dÃ©emploi et aussi les entreprises  - -Une carte dÃ©abonnement JOBTEL: MY JOBCARD DEMANDEUR - o	vous permet de recevoir les offres dÃ©emploi de maniÃ©re automatisÃ© selon votre profil et le domaine de recherche.viasms, email ou messagerie vocal - o	LÃ©accompagnement sur toute la procÃ©dure de recherche du candidat  - Participation dÃ©ateliers Co-organisÃ©s avec nos partenaires - o	Faire votre test de personnalitÃ© - o	BÃ©nÃ©ficiez de bon de rÃ©duction avec la carte - -Une carte dÃ©abonnement JOBTEL: MY JOBCARD RECRUTEUR', 'Cheikh Tidiane ', 'Diagne', '774791520', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web', 1, 'Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires  - intÃ©gration de solution', 0, '', 1, 'E-commerce - E-Ã©ducation', 1, 'TÃ©lÃ©coms - Services rÃ©seaux', 'Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications '),
(14, 1, 'STARTUP', 'SARL', 'DG GLOBAL BUSINESS', '2016-05-09', '550 HLM GRAND MEDINE DAKAR', 3, '784576595', 'dgglobus@sen-pass.com', 'www.sen-pass.com', 'DG GLOBUS SARL est une startup Ã© vocation numÃ©rique qui travaille dans la conception et la rÃ©alisation de plateforme digitale en marque grise, la dÃ©matÃ©rialisation des procÃ©dures, le paiement mobile et lÃ©entretien du tourbillon numÃ©rique. ', 'Cheikh', 'DIOUF', '784576595', 1, 'DÃ©veloppement logiciel mÃ©tier', 0, '', 0, '', 1, 'E-Payement, Fintech - E-commerce - E-santÃ©', 0, '', 'Administration/services publics  - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - Banque, finance, assurances '),
(15, 1, 'PME/PMI  ', 'SARL', 'ANDANDO SN', '2018-07-24', '37 CitÃ© CPI VDN, Dakar - SÃ©nÃ©gal', 6, '2.21338E+11', 'contact@andando.sn', 'https://www.andando.sn', 'ANDANDO est une Ã©quipe forte de plusieurs ingÃ©nieurs informatiques avec diverses compÃ©tences et expÃ©riences. Nous sommes une entreprise spÃ©cialisÃ©e dans les technologies de lÃ©information et de la communication. Notre expertise concerne principalement deux volets qui sont lÃ©IngÃ©nierie logicielle et la SÃ©curitÃ© informatique. En plus de ces deux domaines de prÃ©dilections, nous sommes rÃ©ellement engagÃ©s dans le tissu social en dÃ©veloppement des applications come Andando (covoiturage), Dakar By Bus et Andando AcadÃ©mie (e-learning).', 'Moussa', 'DIALLO', '2.21773E+11', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 1, 'IoT (internet des objets), ', 1, 'SÃ©curitÃ©, monitoring - E-Payement, Fintech - E-Ã©ducation', 1, 'TÃ©lÃ©coms - Hosting, cloud', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Education, Formation, RH, Recherche - TÃ©lÃ©communications  - Transport, Logistique'),
(16, 1, 'STARTUP', 'SARL', 'ADNTECH', '2016-01-01', 'Sacre coeur 3', 5, '', 'management@adncorp.com', 'www.adncorp.com', 'Applications de reporting et suivi comptable pour les PME - Applications de reporting rÃ©glementaire pour les microfinances - Vente de Licences et Developpement informatique - Expertise : Big Data, Chatbot, Open Innovation', 'ADNCORP', 'DIOP', '776343174', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile - Autres sous domaines', 0, '', 1, 'Intelligence Artificielle (IA),  - big data, ', 0, '', 0, '', 'Banque, finance, assurances  - Restauration, hÃ©tellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(17, 1, '', 'GIE', 'Fineducation for youth', '2018-03-01', 'Scat Urbam Hann Maristes 1', 4, '+ 221 77 690 96 18', 'foryouthfineducation@gmail.com', '', 'Nous travaillons dans le domaine de l\'Ã©ducation financiÃ©re des jeunes.', 'Mariama', 'NDIAYE', '774895920', 0, '', 0, '', 0, '', 0, '', 0, '', ''),
(18, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'JobsCom', '2017-05-01', 'Diamniadio', 7, '+221785289105', 'Ouzdiop92@gmail.com', '', 'Impression sur support de communication flocage sÃ©rigraphie infographie ', 'Ousmane', 'Diop', '785289105', 0, '', 0, '', 0, '', 0, '', 0, '', 'Marketing et Communication  - Mode, beautÃ©, luxe  - TÃ©lÃ©communications '),
(19, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Monetbil SÃ©nÃ©gal, Ets', '2018-10-30', 'CTIC Dakar', 1, '763566489', 'thierry.nguefack@boorgeon.com', 'www.monetbil.com', 'AgrÃ©gation des mÃ©thodes de paiement pour simplifier les achats en ligne.', 'Yves Thierry', 'NGUEFACK Assong', '763566489', 1, 'Applications web - Applications mobile', 0, '', 0, '', 1, 'E-Payement, Fintech', 0, '', 'Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances  - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme '),
(20, 1, 'STARTUP', 'SAS', 'ZELCASH SAS', '2018-05-02', 'Diorga ChÃ©rif, Rufisque', 1, '338368118', 'contact@zel-cash.com', 'zel-cash.com', 'OpÃ©ration de transfert d\'argent et service financier digitaux.', 'Elhadji Ousmane', 'NDIAYE', '774310305', 0, '', 0, '', 0, '', 0, '', 0, '', 'Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances '),
(21, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Interface', '2017-04-26', 'Sicap SacrÃ© Coeur III Pyrotechnie Lot 85 B 4Ã©me Ã©tage', 8, '338250605', 'support@interface.sn', 'www.interface.sn', 'Le nouveau concept trÃ©s innovant BEINDAY vous permet 0 seulement dÃ©Ã©tre  ONLINE  gratuitement via son rÃ©seau avec le canal des rÃ©seaux sociaux mais aussi de prÃ©server et de protÃ©ger notre environnement qui utilise encore, pour la plupart, les supports de communication classiques Ã© base de papier. Contrairement Ã© BEINDAY qui propose lÃ©injection de contenus via le wifi monÃ©tisÃ© dÃ©oÃ© le slogan Ã© free is green Ã©.', 'Magatte', 'SYLLA', '775419113', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'Terminaux mobiles et accessoires ', 1, 'IoT (internet des objets),  - big data, ', 1, 'free wifi', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - Energie et Ã©nergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - TÃ©lÃ©communications '),
(22, 1, 'PME/PMI  ', 'SUARL', 'Cosmos Multimedia', '2018-03-07', 'SICAP SACRE COEUR 1', 2, '775088500', 'simel80@hotmail.fr', 'EN COURS DE CONSTRUCTION', 'CrÃ©Ã©e en 2018, notre objectif est dÃ©accompagner les structures PME, PMI dans le dÃ©veloppement de leur visibilitÃ© sur les supports numÃ©riques, mais aussi amÃ©liorer lÃ©image de marque sur les nouvelles technologies avec une communication maitrisÃ©e basÃ©e sur la vidÃ©o web marketing sensoriel (reportage, documentaires, visio Web, mobile, rÃ©seaux sociaux...) Nous proposons Ã©galement des ITV avec des journalistes reporters issus de grands mÃ©dias. Choisissez votre package de diffusion ( TÃ©lÃ©vision /media en ligne etc..) Nous nous occupons de Tout ! -  -  - DÃ©veloppement de site web, application Mobile et sÃ©c', 'Massamba', 'THIAM', '33674346585', 1, 'Applications web - Applications mobile', 0, '', 0, '', 1, 'SÃ©curitÃ©, monitoring', 1, 'Services rÃ©seaux - Hosting, cloud - Conseil en SÃ©curitÃ© Informatique', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - Energie et Ã©nergies renouvelables - Banque, finance, assurances  - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Marketing et Communication  - Mode, beautÃ©, luxe  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - Emploi, RH, Services Ã© la personne  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications '),
(23, 1, 'STARTUP', 'SARL', 'GIGA DEVELOP', '2016-06-16', '1bis rue masclary x allÃ©es Robert Delmas', 6, '77 568 00 00', 'gigadevelopsenegal@gmail.com', '', 'GIGA DEVELOP -  LÃ©innovation technologique au service de la population  - GIGA est spÃ©cialisÃ©e dans le domaine des nouvelles Technologies de lÃ©Information et de la Communication (T.I.C.) plus particuliÃ©rement dans les domaines suivants : - Ã©	DÃ©veloppement de logiciels et dÃ©outils dÃ©analyse de donnÃ©es - Ã©	SystÃ©me de paiement  - Ã©	Objets connectÃ©s - Ã©	SystÃ©me de gÃ©olocalisation et de tracking - Ã©	Big-Data -  - il crÃ©e un environnement dÃ©affaires optimal avec une qualitÃ© de service incomparable, participe Ã© placer le SÃ©nÃ©gal sur un sentier de croissance plus Ã©levÃ© par lÃ©exploitation des avantages comparatifs ', 'Cherif ', 'DJIBA', '775680000', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'Ordinateurs et Ã©quipements informatiques', 1, 'IoT (internet des objets),  - big data, ', 1, 'E-Payement, Fintech', 0, '', 'Economie Sociale &amp;Solidaire  - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - Transport, Logistique'),
(24, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'AGRITECH-SOLUTIONS', '2018-01-01', 'Dakar,libertÃ©', 1, '778045034', 'techagrisolutions@gmail.com', 'agritechsolutions.sn', 'TIC,agricole', 'Makhtar', 'DIOP', '778045034', 1, 'DÃ©veloppement logiciel mÃ©tier - Applications web - Applications mobile - Autres sous domaines', 1, 'Composants Ã©lectroniques et assemblage  - Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires ', 0, '', 0, '', 0, '', ''),
(25, 1, 'STARTUP', 'SARL', 'NOTERKO ', '2018-01-05', '2987D Sicap Dieuppeul 4 Dakar', 2, '776472396', 'contact@noterko.com', 'www.noterko.com', 'EnquÃ©tes de satisfaction clients, collecte des donnÃ©es clients, sondage via plateforme NoterKo, formation accueil clientÃ©le ', 'Nancy', 'Camara', '776472396', 1, 'Applications web', 0, '', 1, 'big data, ', 0, '', 1, 'Hosting, cloud', 'Administration/services publics  - SantÃ©, bien Ã© Ã©tre  - Banque, finance, assurances  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie '),
(26, 1, 'STARTUP', 'SUARL', 'Black Star Technologies SÃ©nÃ©gal', '2017-06-08', 'Villa 1304, HLM Grand-Yoff, Dakar - SÃ©nÃ©gal', 30, '2.21339E+11', 'contact@blackstar-tech.com', 'www.blackstar-tech.com', 'DÃ©veloppement d\'applications (web et mobile) dans les 3 domaines suivants: -  - 1 - Solutions de tÃ©lÃ©phonie d\'entreprise: centre d\'appels, serveurs vocaux, plateforme SMS -  - 2 - MonÃ©tique et solutions de paiement Ã©lectronique (Mobile Banking, eWallet, transfert...) -  - 3 - BiomÃ©trie et cartes d\'identification (cartes Ã© puce, cartes magnÃ©tiques, PVC...) -  - Services BPO(Externalisation des processus mÃ©tiers)', 'Mamadou Lamine ', 'KA', '2.21769E+11', 1, 'DÃ©veloppement logiciel mÃ©tier - Applications web - Applications mobile - BiomÃ©trie, monÃ©tique, centres d\'appels, serveurs vocaux', 0, 'Ordinateurs et Ã©quipements informatiques', 0, '', 0, '', 0, '', 'Administration/services publics  - Banque, finance, assurances  - TÃ©lÃ©communications '),
(27, 1, 'PME/PMI', 'GIE', 'HOUDA SYSTEME', '2009-09-05', 'ANGLE 28 EN FACE STATION MAACK', 4, '33 978 47 44 - 77 844 79 80', 'cheikhouna.houda@gmail.com', '', 'dÃ©senveloppent et distribution des logiciels de gestion commerciale et de la comptabilitÃ© generale', 'Cheikhouna', 'LO', '778447980', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 0, '', 0, '', 'Commerce, agroalimentaire, distribution, import &amp;export  - Emploi, RH, Services Ã© la personne  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(28, 1, 'PME/PMI', 'GIE', 'FREELAB', '2016-05-07', 'mamelles cite elevage', 5, '773842905', 'mohamedfall74@gmail.com', '', 'NOUS CONCEVONS DES DISPOSITIFS ELECTRONIQUES DANS PLUSIEURS DOMAINES: SANTE,ENVIRONNEMENT,AGRICULTURE - EX: ELECTROCARDIOGRAMME CONNECTE,SYSTEME D\'IRRIGATION AUTOMATIQUE...', 'mohamed', 'fall', '773842905', 1, 'Applications web', 1, 'Composants Ã©lectroniques et assemblage  - Terminaux mobiles et accessoires ', 1, 'Animation 3D,                                 - IoT (internet des objets),  - Intelligence Artificielle (IA),  - big data,  - Drone, robotique - AR/VR (rÃ©alitÃ©s augmentÃ©es/rÃ©alitÃ©s virtuelles),', 1, 'SÃ©curitÃ©, monitoring - E-santÃ© - E-agriculture - E-Ã©ducation', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(29, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'ADINKRA CONSULTING ', '2018-02-11', 'Ngor, Almadies ', 4, '+221 766132859', 'akomatsrilola@gmail.com', 'www.adinkra-consulting.com', 'ADINKRA Consulting est une agence de communication en Afrique de lÃ©Ouest, dÃ©terminÃ©e Ã© aider les entrepreneurs, les organisations socialement responsables et les individus oeuvrant dans les domaines de lÃ©agriculture et du dÃ©veloppement Ã© avoir un impact social et durable.', 'AKOMATSRI', 'Lola', '766132859', 1, 'Applications web - Applications mobile', 0, '', 0, '', 1, 'E-agriculture - E-Ã©ducation', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(30, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'SALOUM TIC SERVICES', '2016-11-24', 'BONGRE KAOLACK', 2, '772057671', 'ndeyemaremen1@gmail.com', '', 'PRESTATAIRE DE FORMATION EN INFORMATIQUE', 'MARIAMA', 'NDIAYE', '772057671', 0, '', 1, 'Terminaux mobiles et accessoires ', 0, '', 1, 'E-Payement, Fintech - E-Ã©ducation', 0, '', 'Administration/services publics  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Education, Formation, RH, Recherche'),
(31, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Adji Informatique', '2017-06-02', 'Rue 57 x 701 Fann Hock', 5, '784513505', 'ibrahima@sentools.net', '', '', 'Ibrahima', 'Sene', '784513505', 1, 'Base de donnÃ©es - Applications web - Applications mobile', 1, 'Composants Ã©lectroniques et assemblage  - Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires ', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - AR/VR (rÃ©alitÃ©s augmentÃ©es/rÃ©alitÃ©s virtuelles),', 0, '', 0, '', 'Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - MÃ©dia sociaux/RÃ©seaux Sociaux  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Education, Formation, RH, Recherche - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications '),
(32, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Pragma-tics', '2017-02-16', '1,Rue du Lieutenant Colonel Pierre Faye, Zone A Dakar-SÃ©nÃ©gal', 3, '776500852', 'pragmaticsenegal@gmail.com', 'www.pragma-tics.net', 'Pragma-tics est une entreprise informatique spÃ©cialisÃ©e dans lÃ©ingÃ©nierie logicielle, la conception de sites internet et d\'applications mobiles natives. - Nous concevons des progiciels de gestion hÃ©bergÃ©s sur notre cloud SaaS et accessibles via les navigateurs Web ne nÃ©cessitant aucune installation sur un poste de travail.', ' Papa Amath ', 'Diouf', '776500852', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances  - MÃ©dia sociaux/RÃ©seaux Sociaux  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(33, 1, 'STARTUP', 'SARL', 'COLISDAYS', '2017-03-01', '155 citÃ© des impÃ©ts et domaines Patte d\'oie Nord', 0, '777475765', 'contact@colisdays.com', 'www.colisdays.com', 'Colisdays est une plateforme communautaire qui met en relation des expÃ©diteurs avec des voyageurs profitant dÃ©un dÃ©placement dÃ©jÃ© prÃ©vu pour transporter des colis ou documents. -  - Ce systÃ©me gagnant-gagnant favorise un nouveau mode dÃ©envoi et de suivi de colis : pour lÃ©expÃ©diteur, il sÃ©agira dÃ©avoir un moyen alternatif dÃ©envoyer des colis Ã© des tarifs compÃ©titifs et pour le voyageur de rentabiliser son dÃ©placement en avion ou en voiture par le biais de ses kilos restants.', 'MACTAR', 'SYLLA', '777475765', 0, '', 0, '', 0, '', 1, 'E-commerce - Autres (Ã© prÃ©ciser)', 0, '', 'Transport, Logistique'),
(34, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Massala Services', '2013-01-01', '99 CitÃ© Djily Mbaye', 1, '+221776275258', 'mouna.mbacke@gmail.com', 'www.e-diaba.com', 'Vente de produits de beautÃ© fabriques par des entrepreneurs africains', 'Maimouna', 'Mbacke', '776275258', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'SantÃ©, bien Ã© Ã©tre  - Mode, beautÃ©, luxe '),
(35, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'BUUTIC', '2017-02-02', 'Jokkolabs, SacrÃ© coeur 3 Villa NÃ© 9653 , 4eme phase, 41 Voie de degagement N,', 4, '+221781464694', 'buuticservice@gmail.com', 'buutic.business.site', 'Service aux entreprises', 'L1s Dione', 'BIAGUI', '781464694', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires ', 1, 'IoT (internet des objets),  - big data, ', 1, 'E-Payement, Fintech - E-commerce - E-santÃ© - E-agriculture - E-Ã©ducation', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - Banque, finance, assurances  - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications '),
(36, 1, 'STARTUP', 'GIE', 'agroproduct consulting group ', '2016-01-01', 'sam kaolack lot 66 angle sp', 4, '781683014', 'francoismariasene@yahoo.fr', '', 'Entreprise agroalimentaire spÃ©cialisÃ©e dans la production et la transformation du moringa bio ', 'FranÃ©ois maria ', 'sÃ©ne ', '781683014', 0, 'Autres sous domaines', 0, 'Autres Ã©quipements', 0, 'Autres (Ã© prÃ©ciser)', 1, 'E-commerce - E-agriculture', 0, 'agriculture ', 'Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - Restauration, hÃ©tellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne '),
(37, 1, 'STARTUP', 'GIE', 'Earth GÃ©omatique', '2018-08-07', 'babacarfall.92@gmail.com', 3, '773080399', 'abadjibadji@gmail.com', 'snsig@gmail.com', 'Entreprises offrant des services informatiques accÃ©s dans les technologies gÃ©ospatiales', 'Amezedine younoussa ', 'Badji', '772238635', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 1, 'Animation 3D,                                 - Drone, robotique', 1, 'E-commerce - E-agriculture - E-Ã©ducation', 0, '', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Marketing et Communication '),
(38, 1, 'STARTUP', 'GIE', 'e-Geo', '1900-01-01', '', 0, '', '', '', '', 'Amzedine Younoussa Ben Yacoub', 'BADJI', '772238635', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 1, 'Animation 3D,                                 - Intelligence Artificielle (IA),  - big data,  - Drone, robotique', 1, 'E-commerce - E-agriculture - E-Ã©ducation', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(39, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Xilembane TELECTRON SÃ©nÃ©gal', '2015-06-29', 'Parcelles Assainies U 15', 1, '772319736', 'telectronsenegal@gmail.com', '', 'L\'entreprise devrait fournir des services en sÃ©curitÃ© Ã©lectronique et en infrastructure tÃ©lÃ©coms et informatique. - Peinant Ã© dÃ©coller, je travaille pour une entreprise de la place', 'Papa Birame ', 'BEYE', '772319736', 0, '', 1, 'Composants Ã©lectroniques et assemblage  - SÃ©curitÃ© Ã©lectronique et cÃ©blage informatique', 0, '', 0, '', 1, 'TÃ©lÃ©coms - Services rÃ©seaux', 'Administration/services publics  - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Energie et Ã©nergies renouvelables - Mode, beautÃ©, luxe  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - TÃ©lÃ©communications '),
(40, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'groupe kawsara', '2011-05-06', 'Rufisque coloban', 102, '774292340', 'cheikhibradieng607@gmail.com', 'wwwgkawsara', 'EnvoyÃ© des colis numÃ©rique et info', 'cheikh ibra', 'dieng', '774292340', 0, '', 0, '', 0, '', 1, 'E-Payement, Fintech - E-commerce - Transport Logistique', 0, '', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp;export  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - logistiques'),
(41, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'SENDEAL.SN', '2015-06-25', 'Nord foire villa 10,3Ã©me Etage rue prolongÃ©e SDE', 5, '770932214', 'sendeal.sn@gmail.com', 'www.sendeal.sn', 'Sendeal.sn  est le pionnier sÃ©nÃ©galais de lÃ©achat groupÃ©. Nous proposons des bons plans Ã© sÃ©offrir ou Ã© offrir : sport, beautÃ©, bien-Ã©tre, restaurants, loisirs, shopping, sorties, voyages... Uniquement des bons plans nÃ©gociÃ©s au meilleur prix chez les commerÃ©ants de votre ville. - Sendeal.sn ancre son identitÃ© Ã© la frontiÃ©re de trois tendances : - -le dÃ©veloppement du e-commerce, - -le besoin dÃ©acheter moins cher  - -et lÃ©aspiration Ã© consommer mieux et proche de chez soi. - Devant un large choix de produits lÃ©achat groupÃ© vous permet :De vous offrir des expÃ©riences uniques que vous nÃ©auriez jamais - ', 'SAIDOU', 'GUISSE', '770932214', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - site web et plateforme sms marketing', 0, '', 0, '', 1, 'E-Payement, Fintech - E-commerce - E-agriculture - E-Ã©ducation', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Marketing et Communication  - Mode, beautÃ©, luxe  - AmÃ©nagement dÃ©intÃ©rieur et dÃ©extÃ©rieur  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - TÃ©lÃ©communications  - Transport, Logistique'),
(42, 1, 'PME/PMI  ', 'SARL', 'DMS Sarl ', '2018-03-01', 'Thies Senegal ', 9, '768502222', 'dmssarlthies@gmail.com', 'www.dmssenegal.com', 'Recyclage et fabrication de tuyaux goute Ã© goute et tube orange ', 'Mamadou ', 'Diaw', '782902071', 0, '', 0, '', 1, 'Animation 3D,                                ', 1, 'E-agriculture - E-Ã©ducation', 1, 'Services rÃ©seaux', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Energie et Ã©nergies renouvelables'),
(43, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'SUPA-DEV', '2018-05-07', '109-B Sicap Mbao', 1, '+221771827530', 'habib92m@gmail.com', 'www.super-dev.com', 'INGÃ©NIERIE LOGICIEL - PRESTATION DE SERVICES - CRÃ©ATION ET VENTE DE LOGICIEL -  ', 'Habib BaÃ©dy', 'SOW', '2.21772E+11', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Economie Sociale &amp;Solidaire  - Transport, Logistique'),
(44, 1, 'STARTUP', 'SARL', 'Sunubus', '2017-12-20', 'Dakar SacrÃ© coeur Pyrotechnique derriere agence senelec 10600', 5, '+221772704731', 'contact@sunubus.com', 'www.sunubus.com', '', 'Papa Mor', 'Niane', '2.21773E+11', 1, 'DÃ©veloppement logiciel mÃ©tier - Applications web - Applications mobile', 0, '', 1, 'Intelligence Artificielle (IA), ', 1, 'E-Payement, Fintech - E-commerce - Smart Cities', 0, '', 'Transport, Logistique'),
(45, 1, 'PME/PMI  ', 'GIE', 'AFRIKA BIO', '2017-09-10', 'LibertÃ© 4 ', 2, '+221781376178/773442970', 'contact@afrikabio.bio', 'Facebook.com/afrikabioofficial', 'Afrika bio sÃ©opÃ©re dans la distribution de produits bio et naturelles Made in Africa.  - LÃ©idÃ©e globale Ã©tant de prÃ©senter des produits dÃ©une qualitÃ© Ã©galant les standards internationaux.', 'Matar', 'Coume', '2.21781E+11', 0, '', 0, '', 0, '', 0, '', 0, '', 'Commerce, agroalimentaire, distribution, import &amp;export '),
(46, 1, 'PME/PMI  ', 'GIE', 'NET SOLUTIONS SENEGAL', '2016-05-16', 'KEUR MASSAR', 2, '77 612 49 97', 'netsolutions.sn@gmail.com', 'facebook.com/netsolutions.sn', 'Informatique - TÃ©lÃ©communication - Communication - GÃ©nie Civil', 'Mamadou Kabir', 'THIAM', '2.21776E+11', 0, '', 1, 'Composants Ã©lectroniques et assemblage  - Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires ', 0, '', 1, 'SÃ©curitÃ©, monitoring', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp;export  - Culture, Image, Media ; multimÃ©dia, audiovisuel - AmÃ©nagement dÃ©intÃ©rieur et dÃ©extÃ©rieur  - MÃ©dia sociaux/RÃ©seaux Sociaux  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications '),
(47, 1, 'STARTUP', '', 'Lifantou SAS', '2017-06-15', '27C CitÃ© Soprim', 2, '2.21784E+11', 'awa.thiam@lifantou.com', 'www.lifantou.com', 'Lifantou est une plateforme d\'accompagnement Ã© la production et Ã© la distribution alimentaire. Nous mettons en relation les producteurs et les cantines grÃ©ce Ã© un systÃ©me d\'information gÃ©ographique basÃ© sur la cartographie et l\'imagerie satellitaire ', 'Awa', 'Thiam', '783749349', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web', 0, '', 1, 'Imagerie satellitaire et SIG ', 1, 'E-Payement, Fintech - E-commerce - E-agriculture - Nutrition et distribution ', 0, '', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - TÃ©lÃ©communications '),
(48, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'MY TERANGA', '2018-02-13', 'Saint-L1s du SÃ©nÃ©gal, Ngallele ', 4, '+221771390381', 'ababacarsadikhniang12@gmail.com', 'www.myterangasn.com', 'MY TERANGA est une plateforme de promotion du tourisme culturel et educatif Ã© travers les sÃ©vices tels quels: decouvertes des sites historique touristique et culturel en ligne et le service de package en ligne permettant aux populations locales, touristes et visiteurs d\'avoir toutes les commoditÃ©s nÃ©cessaires  (logement, transport, restauration et autres services touristiques) pour dÃ©couvrir ces sites et patrimoine et vivre une expÃ©rience unique.', 'Ababacar Sadikh', 'Niang', '771390381', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Culture, Image, Media ; multimÃ©dia, audiovisuel - Autres Ã© prÃ©ciser'),
(49, 1, 'STARTUP', 'GIE', 'Espaces Topatoo', '2015-10-19', '', 0, '33 897 20 49 / 77 936 81 15 / 77 705 98 69', 'espacestopatoo@gmail.com', '', '', 'Mouhamadou ', 'Gueye', '776095329', 1, 'Programmation informatique', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 0, '', 0, '', 'Economie Sociale &amp;Solidaire  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Education, Formation, RH, Recherche - Tourisme Culturel '),
(50, 1, 'STARTUP', 'SARL', ' WÃ©TU Digital Lab ', '2017-02-20', 'LibertÃ© 6 Extension CitÃ© JCL NumÃ©ro 122 B/ 1er Etage Gauche', 10, '782199410', 'info@watudigital.com', 'www.watudigital.com', 'WÃ©TU Digital Lab est une agence de communication opÃ©rationnelle digitale pour le dÃ©veloppement rural et le marketing territorial. Nous sommes trÃ©s alerte sur les questions de digitalisation et rÃ©solument engagÃ©s pour relever les dÃ©fis liÃ©s Ã© la formation des jeunes et femmes pour un entrepreneuriat rÃ©flÃ©chi en Afrique. -  - GrÃ©ce Ã© une maÃ©trise efficiente de la communication socionumÃ©rique, Nous vous offrons des solutions innovantes en vue de  Gagner en visibilitÃ© Ã© AccroÃ©tre lÃ©engagement des communautÃ©s Ã© Renforcer la crÃ©dibilitÃ© de vos partenaires .', 'MIKAILA', 'ISSA ABRAMANE', '708028837', 0, '', 0, '', 0, '', 1, 'E-agriculture', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Education, Formation, RH, Recherche'),
(51, 1, 'PME/PMI  ', 'SARL', 'GLOBAL COMPUTER SOLUTIONS SARL', '2000-01-01', 'Sacre coeur II villa NÃ© 8651', 7, '33 869 11 58', 'gcsolutions@gcsolutions.sn', 'www.gcsolutions.sn', 'SystÃ©me et ingÃ©nieurie informatique', 'El hadji Mamadou Laye', 'Ndiaye', '778299679', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'Composants Ã©lectroniques et assemblage  - Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires ', 0, '', 1, 'SÃ©curitÃ©, monitoring - E-Payement, Fintech - E-commerce - E-santÃ© - E-agriculture - E-Ã©ducation', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - Energie et Ã©nergies renouvelables - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Marketing et Communication  - Mode, beautÃ©, luxe  - AmÃ©nagement dÃ©intÃ©rieur et dÃ©extÃ©rieur  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Industrie, Mines - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications  - Transport, Logistique'),
(52, 1, 'STARTUP', 'SA', 'CartaLink SASU', '2016-04-28', '252, citÃ© AssemblÃ©e Nationale, Dakar, SÃ©nÃ©gal', 5, '770983177', 'latyr.senghor@cartalink.com', 'www.cartalink.com', 'DÃ©veloppements d\'applications digitales pour entreprises.', 'Latyr', 'Senghor', '770983177', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile - MonÃ©tique, consultance, outsourcing.', 1, 'Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires ', 1, 'big data, ', 1, 'SÃ©curitÃ©, monitoring - E-Payement, Fintech - E-commerce', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - Energie et Ã©nergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Marketing et Communication  - Mode, beautÃ©, luxe  - AmÃ©nagement dÃ©intÃ©rieur et dÃ©extÃ©rieur  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Industrie, Mines - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications  - Transport, Logistique'),
(53, 1, 'STARTUP', 'SARL', 'BAAMTU', '0000-00-00', 'ouest foire, citÃ© cosapac lot 10', 22, '338206196', 'contact@baamtu.com', 'www.baamtu.com', 'baamtu est dans l\'ingÃ©nierie logicielle et dans le big data analytic', 'Mohamed Moustapha ', 'Diouf', '786393838', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 0, '', 1, 'E-santÃ© - E-Ã©ducation', 1, 'TÃ©lÃ©coms - Hosting, cloud', 'Administration/services publics  - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances  - Restauration, hÃ©tellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications  - Transport, Logistique'),
(54, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'Agence Consulting-Tech', '2018-01-16', 'Ouakam, en face de la mosquÃ©e de la DivinitÃ© ', 1, '+2211773344921', 'alamine@africa2dg.org', '', 'Agence Consulting-Tech est une entreprise numÃ©rique de services. Nous mettons en place des solutions de collaboration pour faciliter la communication interne et externe de l\'entreprise. - Ensemble consolidons votre croissance avec votre transformation digitale', 'Mouhamadou Lamine Bara ', 'Diagne', '7733449921', 1, 'Applications web', 0, '', 0, '', 0, '', 0, '', 'Marketing et Communication  - Restauration, hÃ©tellerie  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(55, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'APPS 1 GLOBAL', '2018-06-15', 'ROUTE DE NGOR, LES ALMADIES DERRIERE LE RESTAURANT LE KATIA, DAKAR', 5, '33 820 82 40', 'admin@apps1global.com', 'www.apps1global.com', 'RÃ©alisation de plateformes numÃ©riques, Ã©dition de livres, conseil en communication, publicitÃ©.', 'Coumba', 'Ndiaye', '776098160', 1, 'Base de donnÃ©es - Applications web - Applications mobile', 0, '', 0, 'IoT (internet des objets), ', 1, 'E-commerce - E-santÃ©', 1, 'Hosting, cloud', 'Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux '),
(56, 1, 'PME/PMI  ', 'SARL', 'AK-Project', '2014-07-23', '1iere impasse Avenue Bourguiba, Dakar', 15, '33 860 78 72', 'julien@ak-project.com', 'www.ak-project.com', 'Nous travaillons pour tous types d\'acteurs institutionnels, publics et privÃ©s. Parmi les nombreuses entreprises qui nous font confiance, nous comptons la plupart des grands comptes prÃ©sents au SÃ©nÃ©gal. -  - OrientÃ©s recommandations stratÃ©giques, nous avons une vision globale de la communication digitale de nos clients en assurant des rÃ©sultats immÃ©diats et des bÃ©nÃ©fices sur le long terme. Nous internalisons Ã©galement un grand nombre de fonctions pour une meilleure rÃ©activitÃ© face Ã© nos clients. CrÃ©ation graphique, DÃ©veloppement, RÃ©dactionnel, Gestion de projet sont Ã© la base note savoir.', 'Julien', 'MALLE', '778193890', 0, '', 0, '', 0, '', 0, '', 0, '', 'Marketing et Communication '),
(57, 1, 'PME/PMI  ', 'SA', 'SOLID', '2005-12-19', '4 Cite Comico 3 VDN', 19, '776399565', 'solid@solid.sn', 'www.solid.sn', '', 'Moustapha', 'DIOP', '776399565', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 1, 'big data,  - Distribution de musique Digitale en ligne', 1, 'SÃ©curitÃ©, monitoring - E-Payement, Fintech - E-commerce', 1, 'Hosting, cloud', 'Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications '),
(58, 1, 'PME/PMI  ', 'SARL', 'PROSE', '2010-06-17', '4250 SICAP Amitie 3 Dakar', 8, '338651150', 'prose@prose.sn', 'www.prose.sn', 'IngÃ©nierie Logicielle', 'Moustapha', 'DIOUF', '776470760', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 0, '', 1, 'E-Payement, Fintech - E-santÃ© - E-agriculture', 0, '', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export '),
(59, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'DIAMALAYE SERVICES TELECOMS INFORMATIQUE', '2016-01-01', 'GUEDIAWAYE BAYE LAYE WAKHINANE NIMZAT', 1, '764630163', 'diamalayeservice@zoho.com', '', 'prestation de service , commerce marchandise divers import export', 'ABDALLAH ', 'NDIAYE', '', 1, '', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 0, '', 0, '', 'SantÃ©, bien Ã© Ã©tre  - Emploi, RH, Services Ã© la personne '),
(60, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'THIAM INFORMATIQUE', '2010-01-15', 'quartier pont', 4, '77 243 63 72', 'adamahiam21@gmail.com', '', 'Installation systÃ©me Windows-Mac -linux Ubuntu etc... et rÃ©paration imprimante et photocopie. DÃ©pannage Ã©lectronique des carte mÃ©res et cÃ©blage rÃ©seau internet des camÃ©ra', 'Adama Galobel', 'THIAM', '772436372', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es', 1, 'Composants Ã©lectroniques et assemblage  - Ordinateurs et Ã©quipements informatiques', 0, '', 1, 'E-commerce', 1, 'Services rÃ©seaux', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp;export  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Emploi, RH, Services Ã© la personne  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(61, 1, 'PME/PMI  ', 'SARL', 'JALAL ENTREPRISE SERVICES', '2011-10-13', 'LIBERTE 6 EXTENSION RUE HLM GRAND YOFF', 5, '338276350', 'jalalsarl@orange.sn', 'www.jalalservices.sn', 'Prestations de services', 'Abdourahmane', 'Sall', '777153422', 1, 'Applications web', 1, 'Composants Ã©lectroniques et assemblage ', 1, 'big data, ', 1, 'SÃ©curitÃ©, monitoring', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Commerce, agroalimentaire, distribution, import &amp;export  - ElectricitÃ©, Froid, Informatique, Promberie, BTP'),
(62, 1, 'PME/PMI  ', 'SARL', 'Finance Expertise Technologie', '2009-01-01', 'Mermose Comico NÃ©60', 30, '338606760', 'manager@finetechgroupe.com', 'www.finetechgroupe.com', 'SociÃ©tÃ© informatique, fournisseur des produits et services informatiques et tÃ©lÃ©communications. ', 'Mamadou ', 'Diop', '338606760', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'MatÃ©riels Telecom', 0, '', 0, '', 1, 'TÃ©lÃ©coms', 'Administration/services publics  - Banque, finance, assurances '),
(63, 1, 'PME/PMI  ', 'SARL', 'SYSCOM TECHNOLOGY', '2008-08-14', 'CITE KEUR GORGUI LOT 60', 10, '338670577', 'direction@syscom-technology.com', 'www.syscom-technology.com', 'IntÃ©grateur de solutions informatique, Impression numÃ©rique', 'Amadou Gueye', 'Cissoko', '774347718', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 1, 'SÃ©curitÃ©, monitoring', 1, 'Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Marketing et Communication  - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(64, 1, 'STARTUP', 'SA', 'AYKOUM GROUP SAS', '2017-01-01', '3 RUE BERANGER X FERRAUD DAKAR PLATEAU', 1, '781540519', 'aykoumgroup@gmail.com', 'www.batipay.com', 'Ecommerce /marketplace: achat, vente et payement de produits/ services pour l\'habitat', 'Nouha', 'Sagna', '766490856', 0, '', 0, '', 0, '', 1, 'E-Payement, Fintech - E-commerce', 0, '', 'Commerce, agroalimentaire, distribution, import &amp;export  - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux '),
(65, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'DIA PRO MEDIA', '2016-01-17', 'Thies', 1, '775733879', 'diaproibou@gmail.com', 'Page Facebook / DIA PRO MEDIA', 'DIA PRO MEDIA est une structure en multimÃ©dia qui dÃ©veloppe l\'audiovisuel ,le webdesign  et le web master', 'Ibrahima', 'DIA', '', 0, '', 0, '', 0, '', 0, '', 0, '', 'Culture, Image, Media ; multimÃ©dia, audiovisuel'),
(66, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Urban News SENEGAL', '2019-06-24', 'Hann Bel-air', 7, '77 302 59 47', 'urbannewssn@gmail.com', 'urban-news.sn', 'PremiÃ©re plateforme de presse en ligne dÃ©diÃ©e aux cultures urbaines du sÃ©nÃ©gal.', 'Lamine', 'SOW', '781580986', 1, 'Applications web', 0, '', 1, 'ActualitÃ©s, fournir des informations ', 1, 'Musical', 1, 'Internet', 'Culture, Image, Media ; multimÃ©dia, audiovisuel - MÃ©dia sociaux/RÃ©seaux Sociaux '),
(67, 1, 'PME/PMI  ', 'ENTREPRISE INDIVIDUELLE', 'STAR BUSINESS', '2015-01-01', 'Diamaguene dagana', 3, '779001139', 'dgstarbusiness@gmail.com', '', 'Maintenance informatique mÃ©canographe Ã©lectromÃ©canique cÃ©ligraphe transfert d\'argent commerce prestation de services ', 'Abdou ', 'DIEYE', '779001139', 1, 'DÃ©veloppement logiciel mÃ©tier', 1, 'Composants Ã©lectroniques et assemblage  - Ordinateurs et Ã©quipements informatiques', 1, 'Animation 3D,                                ', 1, 'E-Payement, Fintech', 1, 'Services rÃ©seaux', 'Energie et Ã©nergies renouvelables - Culture, Image, Media ; multimÃ©dia, audiovisuel - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Technologies dÃ©entreprises gÃ©nÃ©ralistes ');
INSERT INTO `listestartups` (`id`, `ownerID`, `type`, `statut_juridique`, `denomination`, `date_creation`, `adresse`, `effectif`, `telephone_un`, `email`, `site_web`, `description`, `prenom`, `nom`, `telephone_deux`, `software`, `sous_domaine_soft`, `hardware`, `sous_domaine_hard`, `ict_advance`, `sous_domaine_ict_advance`, `ict_service`, `sous_domaine_ict_service`, `ict_network`, `sous_domaine_ict_network`, `secteur`) VALUES
(68, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'GASBA', '2014-02-01', 'MbodiÃ©ne Podor', 2, '782732508', 'amadou78seck@gmail.com', '', 'Multiservices: photocopie, tirage, traitement, cyber connexion rÃ©sean interne, cours informatique (word, excel, power point , conception de site web), confection de cartes: mariage, visite, membre', 'Amadou', 'SECK', '782732508', 1, 'Applications web', 1, 'Composants Ã©lectroniques et assemblage  - Ordinateurs et Ã©quipements informatiques', 0, '', 0, '', 1, 'Services rÃ©seaux', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Mode, beautÃ©, luxe  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Education, Formation, RH, Recherche'),
(69, 1, 'PME/PMI  ', 'GIE', 'Xuuli Beut', '2013-01-01', 'Medina course  sor saint l1s du SÃ©nÃ©gal', 5, '764809582', 'bgtalle@gmail.com', '', 'Nous avons la serigraphie,l\'infographie et decoration-pub. Notre activitÃ©s consiste Ã© confectionner des logos, reproduire des images,logos et textes sur les tee shirt, casquettes, lacoste etc. Tirage affiches, bandoroles enseignes et table de direction.', 'AllÃ©', 'MBAYE', '774809582', 0, '', 0, '', 0, '', 0, '', 0, '', 'sÃ©rigaphe'),
(70, 1, 'PME/PMI  ', 'SA', 'NEDGESYSTEMS', '2018-01-05', 'SacrÃ© cÃ©ur keur gorgui', 15, '338691413', 'contact@nedgesys.com', 'www.nedgesys.com', 'SociÃ©tÃ© d\'intÃ©gration de services informatiques : installation rÃ©seaux informatiques,ToIP,WIFI,WAN, sÃ©curisation RÃ©seaux informatiques, - Audit, Formation,Cablage informatique et Ã©lectrique ', 'Mamadou', 'Thiam', '338691412', 1, 'Installation Application metier', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 1, 'SÃ©curitÃ©, monitoring', 1, 'Services rÃ©seaux', 'Administration/services publics  - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - Energie et Ã©nergies renouvelables - Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Marketing et Communication  - Mode, beautÃ©, luxe  - AmÃ©nagement dÃ©intÃ©rieur et dÃ©extÃ©rieur  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Industrie, Mines - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - T&e'),
(71, 1, 'PME/PMI  ', 'SARL', 'PlÃ©xus Studios SÃ©nÃ©gal', '2018-01-05', 'Hann Bel air / Yarakh', 10, '78 158 09 86', 'plexusstudiossenegal@gmail.com', '', 'Agence de communication', 'Lamine', 'SOW', '781580986', 0, '', 0, '', 1, 'CrÃ©ation de contenus multimÃ©dias', 0, 'Autres (Ã© prÃ©ciser)', 0, '', 'Culture, Image, Media ; multimÃ©dia, audiovisuel - Marketing et Communication  - MÃ©dia sociaux/RÃ©seaux Sociaux '),
(72, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Astou Dieng', '2016-09-30', 'Thiaroye Azur Mbattal', 0, '774882671', 'diengastou14@gmail.com', 'www.cad-communication.com', 'DÃ©veloppement de sites , applications mobiles - Commnunity management  - Campagnes digitales  - Creations graphiques supports de communication print .', 'Astou', 'Dieng', '', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 0, '', 0, '', 0, '', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp;export  - Marketing et Communication  - Mode, beautÃ©, luxe  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie '),
(73, 1, 'STARTUP', 'GIE', 'Start-It Up(Education NumÃ©rique pour tous)', '2018-01-04', 'Ex Terrain Foyer Rocade Fann Bel Air, BP 10 000 Dakar LibertÃ© SENEGAL', 10, '780132980', 'startitup221@gmail.com', 'https://www.facebook.com/madisn221/', 'Start-It Up est un programme dÃ©initition aux technologies de lÃ©information et de la communication. - A travers des ateliers de formation nous essayons de sensibiliser la population sur les enjeux du numÃ©rique et pour une utilisation sure dÃ©Internet', 'Abdourahmane', 'TraorÃ©', '780132980', 0, '', 0, '', 0, '', 1, 'Education NumÃ©rique', 0, '', 'Culture, Image, Media ; multimÃ©dia, audiovisuel - MÃ©dia sociaux/RÃ©seaux Sociaux  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Sensibilisation NumÃ©rique'),
(74, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'AyudaFund ', '2019-06-07', 'Dakar-SÃ©nÃ©gal ', 2, '78 103 85 93', 'oumouwone@ayudafund.com', 'www.ayudafund.com', 'Donnez lï¿½opportunitï¿½ aux femmes foyers vulnÃ©rables , retraitï¿½s vulnï¿½rables et personnes handicapï¿½es dï¿½avoir une vie descente en investissant votre temps et votre argent dans leurs activitï¿½s gï¿½nï¿½ratrices de revenus.', 'Oumouhane Saoudatou ', 'Wone', '781038593', 1, 'Applications web', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 0, '', 0, '', 'Economie Sociale &amp; Solidaire '),
(75, 1, 'STARTUP', 'GIE', 'SENEBOT', '2018-06-13', 'Mermoz- Dakar', 10, '781582233', 'contact@senebot.com', 'www.senebot.com', 'une Startup qui evolue dans le milieu de la robotique en realisant des projets et qui forme la jeune generation a cela', 'Abdoul Aziz Sy', 'Ndiaye', '771265395', 0, '', 0, '', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA),  - Drone, robotique', 0, '', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Education, Formation, RH, Recherche - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - Robotique'),
(76, 1, 'PME/PMI  ', 'SARL', 'ATELIER DE MAINTENANCE AUTO INDUSTRIEL INSTALLATIONS MICRO IRRIGATIONS ', '2005-01-10', 'Route du Frond de Terre X Rue A', 5, '775218517', 'frontamai@hotmail.fr', '', 'AmÃ©nagement agricole(irrigation en goutte Ã© goutte addiction d\'eau). - Terrassement installation forage systÃ©me automatisation agricole installation serres.', 'Sidy Lamine', 'Diarra', '775218517', 0, '', 0, '', 0, '', 0, '', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export '),
(77, 1, 'PME/PMI  ', 'SARL', 'GOLDEN EYES AFRICA', '2007-01-01', 'LibertÃ© extension', 2, '338670970', 'golden-eyes@orange.sn', '', 'sociÃ©tÃ© d\'intÃ©grateur de services informatiques ', 'Amine', 'KEBE', '338670970', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile - Autres sous domaines', 1, 'Terminaux mobiles et accessoires ', 0, '', 0, '', 1, 'Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Marketing et Communication  - AmÃ©nagement dÃ©intÃ©rieur et dÃ©extÃ©rieur  - Restauration, hÃ©tellerie  - Education, Formation, RH, Recherche'),
(78, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Njureel', '2019-03-26', 'hann Maristes citÃ© Elisabeth Diouf n*12 BIS/', 7, '+221774183376', 'njureelservices@gmail.com', 'www.njureel.com ( en construction )', 'Recherches et dÃ©veloppement de solutions e-santÃ©: developpemnt d\'un systÃ©me de tÃ©lÃ©mÃ©dicine pour les femmes enceintes en milieu rural', 'Awa', 'Ndiaye', '2.21774E+11', 1, 'Base de donnÃ©es - Applications web - Applications mobile', 0, '', 0, '', 1, 'E-Payement, Fintech - E-santÃ©', 0, '', 'SantÃ©, bien Ã© Ã©tre  - Economie Sociale &amp;Solidaire '),
(79, 1, 'PME/PMI  ', 'GIE', 'KAYELEEN INFORMATIQUE', '2015-01-01', 'ZIGUINCHOR', 7, '775447014', 'gerome.sambou@gmail.com', '', 'Formation en informatique et dÃ©ploiement de services informatique', 'Gerome ', 'Sambou', '775447214', 0, '', 0, 'Ordinateurs et Ã©quipements informatiques', 0, '', 0, '', 0, '', 'Administration/services publics  - Education, Formation, RH, Recherche'),
(80, 1, 'STARTUP', 'SUARL', 'Black Star Technologies', '2017-06-07', 'Lot 139; Sicap Foire, Dakar - SÃ©nÃ©gal', 5, '2.21339E+11', 'contact@blackstar-tech.com', 'www.blackstar-tech.com', 'Black Star Technologies est une sociÃ©tÃ© de services numÃ©riques spÃ©cialisÃ©e dans le dÃ©veloppement dÃ©applications et lÃ©intÃ©gration de solutions principalement dans les mÃ©tiers et domaines dÃ©activitÃ© suivants:  - Ã©	BiomÃ©trie et cartes Ã© puce - Ã©	Centres dÃ©appels, IVRs, SMS - Ã©	MonÃ©tique et solutions de paiement - LÃ©atout majeur de Black Star Technologies est sa capacitÃ© Ã© combiner ces diffÃ©rentes technologies pour fournir une solution globale unique aux problÃ©matiques spÃ©cifiques de ses clients.', 'Mamadou Lamine', 'KA', '2.21776E+11', 1, 'DÃ©veloppement logiciel mÃ©tier - Applications web - Applications mobile', 1, 'Lecteurs et imprimantes Ã© cartes, embosseuses, Ã©uipements biomÃ©triques', 0, '', 1, 'E-Payement, Fintech', 1, 'Centres d\'appels, Plateformes SMS, Serveurs Vocaux, IPBX', 'Administration/services publics  - Banque, finance, assurances  - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications '),
(81, 1, 'PME/PMI  ', 'SARL', 'Soyere Consulting', '2004-01-01', '115Rue Carnot Dakar', 5, '338218749', 'contact@soyere.org', 'www.soyere.org', '', 'Nicolas', 'SOYERE', '338218749', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 0, '', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances  - Industrie, Mines - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - Transport, Logistique'),
(82, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'Global Business Solutions', '2017-03-27', 'Mbour/SÃ©nÃ©gal', 4, '777018218', 'oussen91@gmail.com', '', 'Servicesinformatique : formation des Ã©lÃ©ves de la primaire au lycÃ©e', 'Ousmane ', 'SY', '', 0, '', 1, 'Ordinateurs et Ã©quipements informatiques', 1, 'IoT (internet des objets), ', 0, '', 1, 'Services rÃ©seaux', 'Agriculture, Ã©levage ; environnement, pÃ©che - Transport, Logistique'),
(83, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'INTECH', '2012-07-02', 'Parcelles Assainies U8 Dakar', 1, '777617368', 'fatou.diaoune@agence-intech.com', 'www.agence-intech.com', 'CrÃ©action de site web, Application web, Intranet, RÃ©fÃ©rencement web, IntÃ©gration de solution web, Formation, ...', 'Fatou', 'DIAOUNE', '777617368', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - IntÃ©gration, rÃ©fÃ©rencement web, formation', 0, '', 0, '', 1, 'E-commerce - E-santÃ©', 1, 'Hosting, cloud', 'Administration/services publics  - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Energie et Ã©nergies renouvelables - Marketing et Communication  - Mode, beautÃ©, luxe  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie  - Education, Formation, RH, Recherche - Industrie, Mines - Technologies dÃ©entreprises gÃ©nÃ©ralistes '),
(84, 1, 'PME/PMI  ', 'SUARL', 'WEST AFRICAN NETWORKFOR GLOBAL ONLINE (WANGO)', '2015-01-01', 'Hlm grand yoff NÃ©443- immeuble Tabara NGOM 3ieme Ã©tage, Bureau CÃ©', 5, '33 867 72 05  76 645 75 23', 'contact@wango.sn', 'www.wango.sn', 'La consultation dans les rÃ©seaux et les systÃ©mes - L\'audit et diagnostic des systÃ©mes informatiques  - Toutes activitÃ©s d\'hÃ©bergementde donnÃ©es ,de services mangÃ©s et de cloud computing - Le dÃ©veloppement de logiciel, l\'Ã©tude et le conseil en systÃ©me information  - L\'audit de sÃ©curitÃ© et des tests d\'instrusion des systÃ©mes informatiques et rÃ©seaux ; l\'Ã©tude , la conception, le suivi et la rÃ©alisation d\'architecture rÃ©seaux et systÃ©mes informatiques, l\'animation de sÃ©minaires et de sÃ©ances de  formation dans le domaine de l\'informatique , des rÃ©seaux et des tÃ©lÃ©communications', 'Alioune Badara', 'DIOP', '777636445', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 1, 'Ordinateurs et Ã©quipements informatiques - Terminaux mobiles et accessoires ', 1, 'Intelligence Artificielle (IA),  - big data, ', 1, 'SÃ©curitÃ©, monitoring - E-Payement, Fintech - E-santÃ©', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Banque, finance, assurances  - Marketing et Communication  - Restauration, hÃ©tellerie  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - Industrie, Mines - Technologies dÃ©entreprises gÃ©nÃ©ralistes  - TÃ©lÃ©communications '),
(85, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'BONJOUR SENEGAL, BONJOUR SUNUGAL SERVICES, ', '2018-04-09', 'SICAP LIBERTE 5 VILLA NÃ©5351/B Dakar, SÃ©nÃ©gal', 3, '2.21782E+11', 'contact@bonjoursenegal.com', 'https://www.bonjoursenegal.com', 'BONJOUR SENEGAL est une plateforme digitale dÃ©diÃ©e Ã© la promotion de la destination SENEGAL.  - BONJOUR SENEGAL a pour ambition premiÃ©re de dÃ©velopper lÃ©Ã©conomie locale Ã© travers le tourisme en permettant aux sÃ©nÃ©galais de (re) dÃ©couvrir ce magnifique pays !  - Nous souhaitons connecter voyageurs et acteurs locaux du Tourisme car, Ã© l\'Ã©re oÃ© tout se passe sur Internet, trÃ©s peu dÃ©acteurs locaux sÃ©nÃ©galais (hÃ©tels, musÃ©es, maison dÃ©hÃ©tes, activitÃ©s touristiquesÃ©) sont prÃ©sents sur le web.', 'NdÃ©ye Aminata ', 'Voyel', '2.21782E+11', 1, 'Applications web - Applications mobile', 0, '', 0, '', 1, 'E-Tourisme', 0, '', 'Economie Sociale &amp;Solidaire  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - MÃ©dia sociaux/RÃ©seaux Sociaux  - Restauration, hÃ©tellerie '),
(86, 1, 'PME/PMI  ', 'SA', 'MAYI Senegal SAS', '2018-05-16', '07 rue jean mermoz, Dakar, Plateau', 27, '', 'adam.cox@miya-africa.com', 'www.miya-africa.com', 'Purification, Embouteillage &amp;Distribution d\'Eau', 'Adam', 'Cox', '771446129', 0, '', 0, '', 0, '', 0, '', 0, '', ''),
(87, 1, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'PrestaDak', '2015-01-14', 'Sacre coeur 3', 3, '764596001', 'contact@prestadak.com', 'http://prestadak.com', 'Agence web spÃ©cialisÃ©e dans le dÃ©veloppement de plateforme e-commerce, site internet et apllication mobile', 'Mohamadou', 'Ndiaye', '779326509', 1, 'DÃ©veloppement logiciel mÃ©tier - Base de donnÃ©es - Applications web - Applications mobile', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Culture, Image, Media ; multimÃ©dia, audiovisuel - Sport, Jeux vidÃ©o, Loisirs &amp;Tourisme  - Marketing et Communication  - Mode, beautÃ©, luxe  - Restauration, hÃ©tellerie  - Education, Formation, RH, Recherche - Industrie, Mines'),
(88, 1, 'STARTUP', 'SUARL', 'SOXLLA.COM SUARL', '2016-03-18', 'SacrÃ© Coeur 2, Immeuble Sokhna Astou LO - Bloac A', 19, '338643332', 'contact@soxlla.com', 'www.yobuma.com', 'SOXLLA a un produit nommÃ© \"YOBUMA\" qui est une solution de rÃ©servation de billets de bus interurbains. ', 'Sankoung', 'AIDARA', '774120753', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Transport, Logistique'),
(89, 1, 'STARTUP', 'SARL', 'Niokobok', '2012-01-01', 'sud foire villa 142', 9, '771154233', 'team@niokobok.com', 'www.niokobok.com', '', 'Laurant', 'Liautaud', '771987964', 0, '', 0, '', 0, '', 1, 'E-commerce', 0, '', 'Commerce, agroalimentaire, distribution, import &amp;export '),
(90, 1, 'PME/PMI  ', 'SARL', 'SESAM INFORMATICS', '2006-11-30', '28 CITE TEYLIUM VDN BP 11764 DAKAR PEYTAVIN', 30, '338675230', 'contact@sesam.sn', 'www.sesam.sn', 'INTEGRATION DE SOLUTIONS INFORMATIQUES', 'Meuleye', 'MBOUP', '776373772', 0, '', 1, 'MATERIEL DE TELECOMMUNICATION RESEAUX ET SECURITE', 0, '', 0, '', 1, 'TÃ©lÃ©coms - Services rÃ©seaux - Hosting, cloud', 'Administration/services publics  - Banque, finance, assurances  - SÃ©curitÃ© et Cyber sÃ©curitÃ©  - TÃ©lÃ©communications '),
(91, 1, '', 'SARL', 'ANDEL-GHANDI', '2017-01-12', '4 CITE MAMA RHANE OUEST FOIRE', 1, '775369263/778119786', 'andelghandi@gmail.com', '', 'consultant/conseiller en business plan/GAR,gestion/RH - JE fais des Ã©tudes de projets pour les personnes ayant une idÃ©e Ã© concrÃ©tiser et ne savent pas comment la matÃ©rialiser ou qui cherchent un financement  ', 'ROBERT ANDEL', 'SARR', '775369263', 0, '', 0, '', 0, '', 0, '', 0, '', 'Agriculture, Ã©levage ; environnement, pÃ©che - Commerce, agroalimentaire, distribution, import &amp;export  - Restauration, hÃ©tellerie  - Education, Formation, RH, Recherche - Emploi, RH, Services Ã© la personne  - Transport, Logistique - POUR AUTRES LE BATIMENT '),
(93, 1, 'STARTUP', 'SARL', 'DARAL TECHNOLOGIES', '2015-01-01', 'PARCELLES ASSAINIES U 3 VILLA 416', 50, '771026094', 'sow.amadou78@yahoo.fr', 'daralserver.cloudapp.net', 'Besoins  des  Ã©leveurs : - ProblÃ©matiques Ã© rÃ©soudre. - Dans le cadre de la rÃ©duction de la pauvretÃ© et la sauvegarde des acquis des Ã©leveurs ; nous sommes prÃ©occupÃ©s Ã© faire intervenir lÃ©outil informatique au service du monde rural. - On sait que dans le monde actuel toute activitÃ© de dÃ©veloppement peut profiter des acquis de la nouvelle technologie. - Donc lÃ©Ã©levage doit prendre sa place dans le systÃ©me informatique pour apporter des solutions aux flÃ©aux qui habitent ce secteur dÃ©activitÃ©s notamment : - - les Ã©pizooties qui font des ravages pour le cheptel en gÃ©nÃ©ral partout en Afrique et ces dÃ©gÃ©ts s', 'AMADOU', 'SOW', '771026094', 1, 'Base de donnÃ©es - Applications web - Applications mobile', 0, '', 1, 'IoT (internet des objets),  - Intelligence Artificielle (IA), ', 1, 'E-commerce - E-santÃ© - E-agriculture', 1, 'Services rÃ©seaux', 'Administration/services publics  - Agriculture, Ã©levage ; environnement, pÃ©che - SantÃ©, bien Ã© Ã©tre  - Commerce, agroalimentaire, distribution, import &amp;export  - Economie Sociale &amp;Solidaire  - MÃ©dia sociaux/RÃ©seaux Sociaux '),
(94, 1, 'PME/PMI  ', 'SA', 'SOCITECH GUINNEE', '2012-06-21', 'KIPE centre emetteur, commune de ratoma', 8, '669390006', 'guinee@socitech.com', 'www.socitech.com', 'IntÃ©grateurs de solutions informatique (SystÃ©me,rÃ©seau,sÃ©curitÃ©) - DÃ©matÃ©rialisation et Archivage Ã©lectronique de documents - Formation et certification en informatique - Accompagnement et service aprÃ©s vente - Fourniture de matÃ©riel informatique et onduleurs  - Cablage Ã©lectrique,Informatique', 'Jean-Marc BEDJE', 'KOFIA', '669390007', 1, 'Base de donnÃ©es', 1, 'Ordinateurs et Ã©quipements informatiques', 0, '', 1, 'SÃ©curitÃ©, monitoring', 1, 'TÃ©lÃ©coms', 'Administration/services publics  - Banque, finance, assurances  - Industrie, Mines - TÃ©lÃ©communications '),
(96, 13, 'STARTUP', 'ENTREPRISE INDIVIDUELLE', 'MEDINA TECH', '2019-09-02', 'DAKAR', 1, '772257744', 'fila@gmail.com', 'neant', 'creation de logiciel', 'marietou', 'dia', '', 0, '', 0, '', 0, '', 0, '', 0, '', 'soft'),
(100, 1, '', 'ENTREPRISE INDIVIDUELLE', 'Niang&amp;Co', '2005-02-02', 'rue de reims', 4, '784514545', 'admin@gmail.com', 'www.wango.sn', 'ig', 'uyuy', 'yguyg', '', 0, '', 0, '', 0, '', 0, '', 0, '', 'uyfuy');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `listestartups`
--
ALTER TABLE `listestartups`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_ownerId` (`ownerID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `listestartups`
--
ALTER TABLE `listestartups`
  MODIFY `id` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `listestartups`
--
ALTER TABLE `listestartups`
  ADD CONSTRAINT `fk_ownerId` FOREIGN KEY (`ownerID`) REFERENCES `utilisateurs` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
